/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Phone-Number-ID}/block_users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                Version: string;
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        /**
         * Get blocked users
         * @description - Guide: [Block Users](https://developers.facebook.com/docs/business-messaging/whatsapp/block-users)\n    \n- Endpoint reference: [GET WhatsApp Buiness Phone Number > block_users](https://developers.facebook.com/docs/graph-api/reference/whats-app-business-account-to-number-current-status/block_users/#Reading)
         */
        get: operations["getBlockedUsers"];
        put?: never;
        /**
         * Block user(s)
         * @description - Guide: [Block Users](https://developers.facebook.com/docs/business-messaging/whatsapp/block-users)\n    \n- Endpoint reference: [POST WhatsApp Buiness Phone Number > block_users](https://developers.facebook.com/docs/graph-api/reference/whats-app-business-account-to-number-current-status/block_users/#Creating)
         */
        post: operations["blockUserS"];
        /**
         * Unblock user(s)
         * @description - Guide: [Block Users](https://developers.facebook.com/docs/business-messaging/whatsapp/block-users)\n    \n- Endpoint reference: [DELETE WhatsApp Buiness Phone Number > block_users](https://developers.facebook.com/docs/graph-api/reference/whats-app-business-account-to-number-current-status/block_users/#Deleting)
         */
        delete: operations["unblockUserS"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BlockedUser: {
            /** @example whatsapp */
            messaging_product?: string;
            /** @example 16505551234 */
            wa_id?: string;
        };
        PaginationCursors: {
            /** @example eyJvZAmZAzZAXQiOjAsInZAlcnNpb25JZACI6IjE3Mzc2Nzk2ODgzODM1ODQifQZDZD */
            after?: string;
            /** @example eyJvZAmZAzZAXQiOjAsInZAlcnNpb25JZACI6IjE3Mzc2Nzk2ODgzODM1ODQifQZDZD */
            before?: string;
        };
        Paging: {
            cursors?: components["schemas"]["PaginationCursors"];
        };
        GetBlockedUsersData: {
            /**
             * @example {
             *       "0": {
             *         "messaging_product": "whatsapp",
             *         "wa_id": "16505551234"
             *       }
             *     }
             */
            data?: components["schemas"]["BlockedUser"][];
            paging?: components["schemas"]["Paging"];
        };
        BlockedUserOperation: {
            /** @example +16505551234 */
            input?: string;
            /** @example 16505551234 */
            wa_id?: string;
        };
        BlockUsersResult: {
            /**
             * @example {
             *       "0": {
             *         "input": "+16505551234",
             *         "wa_id": "16505551234"
             *       }
             *     }
             */
            added_users?: components["schemas"]["BlockedUserOperation"][];
        };
        UnblockUsersResult: {
            /**
             * @example {
             *       "0": {
             *         "input": "+16505551234",
             *         "wa_id": "16505551234"
             *       }
             *     }
             */
            removed_users?: components["schemas"]["BlockedUserOperation"][];
        };
        BlockUsersData: {
            block_users?: components["schemas"]["BlockUsersResult"];
            /** @example whatsapp */
            messaging_product?: string;
        };
        UnblockUsersData: {
            block_users?: components["schemas"]["UnblockUsersResult"];
            /** @example whatsapp */
            messaging_product?: string;
        };
    };
    responses: {
        /** @description Get blocked users */
        GetBlockedUsersResponse: {
            headers: {
                /** @description CORS policy allowing access from any origin */
                "Access-Control-Allow-Origin"?: string;
                /** @description Alternative service advertisement for HTTP/3 */
                "Alt-Svc"?: string;
                /** @description Cache control directives for the response */
                "Cache-Control"?: string;
                /** @description Connection management directive */
                Connection?: string;
                /** @description Size of the response body in bytes */
                "Content-Length"?: string;
                /** @description Date and time when the response was generated */
                Date?: string;
                /** @description Entity tag for caching and conditional requests */
                ETag?: string;
                /** @description Expiration date for cached responses */
                Expires?: string;
                /** @description Legacy cache control directive */
                Pragma?: string;
                /** @description HSTS header enforcing HTTPS connections */
                "Strict-Transport-Security"?: string;
                /** @description Headers that affect caching and content negotiation */
                Vary?: string;
                /** @description Facebook debug information for troubleshooting */
                "X-FB-Debug"?: string;
                /** @description Facebook Graph API version used for the request */
                "facebook-api-version"?: string;
                /** @description Business use case usage metrics and rate limiting information */
                "x-business-use-case-usage"?: string;
                /** @description Unique identifier for the request for debugging purposes */
                "x-fb-request-id"?: string;
                /** @description Facebook internal revision number */
                "x-fb-rev"?: string;
                /** @description Facebook trace identifier for request tracking */
                "x-fb-trace-id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GetBlockedUsersData"];
            };
        };
        /** @description Block user(s) */
        BlockUsersResponse: {
            headers: {
                /** @description CORS policy allowing access from any origin */
                "Access-Control-Allow-Origin"?: string;
                /** @description Alternative service advertisement for HTTP/3 */
                "Alt-Svc"?: string;
                /** @description Cache control directives for the response */
                "Cache-Control"?: string;
                /** @description Connection management directive */
                Connection?: string;
                /** @description Size of the response body in bytes */
                "Content-Length"?: string;
                /** @description Date and time when the response was generated */
                Date?: string;
                /** @description Expiration date for cached responses */
                Expires?: string;
                /** @description Legacy cache control directive */
                Pragma?: string;
                /** @description HSTS header enforcing HTTPS connections */
                "Strict-Transport-Security"?: string;
                /** @description Headers that affect caching and content negotiation */
                Vary?: string;
                /** @description Facebook connection quality metrics */
                "X-FB-Connection-Quality"?: string;
                /** @description Facebook debug information for troubleshooting */
                "X-FB-Debug"?: string;
                /** @description Facebook Graph API version used for the request */
                "facebook-api-version"?: string;
                /** @description Business use case usage metrics and rate limiting information */
                "x-business-use-case-usage"?: string;
                /** @description Unique identifier for the request for debugging purposes */
                "x-fb-request-id"?: string;
                /** @description Facebook internal revision number */
                "x-fb-rev"?: string;
                /** @description Facebook trace identifier for request tracking */
                "x-fb-trace-id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BlockUsersData"];
            };
        };
        /** @description Unblock user(s) */
        UnblockUsersResponse: {
            headers: {
                /** @description CORS policy allowing access from any origin */
                "Access-Control-Allow-Origin"?: string;
                /** @description Alternative service advertisement for HTTP/3 */
                "Alt-Svc"?: string;
                /** @description Cache control directives for the response */
                "Cache-Control"?: string;
                /** @description Connection management directive */
                Connection?: string;
                /** @description Size of the response body in bytes */
                "Content-Length"?: string;
                /** @description Date and time when the response was generated */
                Date?: string;
                /** @description Expiration date for cached responses */
                Expires?: string;
                /** @description Legacy cache control directive */
                Pragma?: string;
                /** @description HSTS header enforcing HTTPS connections */
                "Strict-Transport-Security"?: string;
                /** @description Headers that affect caching and content negotiation */
                Vary?: string;
                /** @description Facebook connection quality metrics */
                "X-FB-Connection-Quality"?: string;
                /** @description Facebook debug information for troubleshooting */
                "X-FB-Debug"?: string;
                /** @description Facebook Graph API version used for the request */
                "facebook-api-version"?: string;
                /** @description Business use case usage metrics and rate limiting information */
                "x-business-use-case-usage"?: string;
                /** @description Unique identifier for the request for debugging purposes */
                "x-fb-request-id"?: string;
                /** @description Facebook internal revision number */
                "x-fb-rev"?: string;
                /** @description Facebook trace identifier for request tracking */
                "x-fb-trace-id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnblockUsersData"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description CORS policy allowing access from any origin */
        "Access-Control-Allow-Origin": string;
        /** @description Alternative service advertisement for HTTP/3 */
        "Alt-Svc": string;
        /** @description Cache control directives for the response */
        "Cache-Control": string;
        /** @description Connection management directive */
        Connection: string;
        /** @description Size of the response body in bytes */
        "Content-Length": string;
        /** @description Date and time when the response was generated */
        Date: string;
        /** @description Entity tag for caching and conditional requests */
        ETag: string;
        /** @description Expiration date for cached responses */
        Expires: string;
        /** @description Legacy cache control directive */
        Pragma: string;
        /** @description HSTS header enforcing HTTPS connections */
        "Strict-Transport-Security": string;
        /** @description Headers that affect caching and content negotiation */
        Vary: string;
        /** @description Facebook connection quality metrics */
        "X-FB-Connection-Quality": string;
        /** @description Facebook debug information for troubleshooting */
        "X-FB-Debug": string;
        /** @description Facebook Graph API version used for the request */
        "facebook-api-version": string;
        /** @description Business use case usage metrics and rate limiting information */
        "x-business-use-case-usage": string;
        /** @description Unique identifier for the request for debugging purposes */
        "x-fb-request-id": string;
        /** @description Facebook internal revision number */
        "x-fb-rev": string;
        /** @description Facebook trace identifier for request tracking */
        "x-fb-trace-id": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBlockedUsers: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                Version: string;
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["GetBlockedUsersResponse"];
        };
    };
    blockUserS: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                Version: string;
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @example {
                     *       "0": {
                     *         "user": "+16505551234"
                     *       }
                     *     }
                     */
                    block_users?: {
                        /** @example +16505551234 */
                        user?: string;
                    }[];
                    /** @example whatsapp */
                    messaging_product?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["BlockUsersResponse"];
        };
    };
    unblockUserS: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                Version: string;
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @example {
                     *       "0": {
                     *         "user": "+16505551234"
                     *       }
                     *     }
                     */
                    block_users?: {
                        /** @example +16505551234 */
                        user?: string;
                    }[];
                    /** @example whatsapp */
                    messaging_product?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["UnblockUsersResponse"];
        };
    };
}
