/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Message-History-ID}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get WhatsApp Message History Events
         * @description Retrieve paginated message delivery status events for a specific message history entry,
         *     including delivery status occurrences, timestamps, and application information.
         *
         *     **Use Cases:**
         *     - Track detailed message delivery status events and transitions
         *     - Monitor delivery status occurrence timestamps
         *     - Retrieve application information for delivery events
         *     - Debug message delivery issues and status changes
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         *
         *     **Caching:**
         *     Message history events can be cached for short periods, but delivery status events
         *     may change frequently. Implement appropriate cache invalidation strategies.
         *
         *     **Pagination:**
         *     This endpoint supports cursor-based pagination. Use the `after` and `before` cursors
         *     from the response to navigate through results.
         */
        get: operations["getMessageHistoryEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Edge containing message delivery status occurrence with pagination cursor */
        WhatsAppMessageHistoryEventsEdge: {
            /**
             * @description Pagination cursor for this edge
             * @example MTAxNTExOTQ1MjAwNzI5NDE=
             */
            cursor?: string;
            node: components["schemas"]["WhatsAppBusinessMessageDeliveryStatusOccurrence"];
        };
        /** @description Message delivery status occurrence with detailed event information */
        WhatsAppBusinessMessageDeliveryStatusOccurrence: {
            /**
             * @description Unique identifier for the message delivery status occurrence
             * @example 2345678901234567
             */
            id: string;
            delivery_status: components["schemas"]["WhatsAppMessageDeliveryStatus"];
            /**
             * @description Error description if the delivery encountered an error
             * @example Message delivery failed due to invalid phone number
             */
            error_description?: string;
            /**
             * Format: int64
             * @description Unix timestamp when the delivery status occurrence happened
             * @example 1640995200
             */
            occurrence_timestamp: number;
            /**
             * Format: int64
             * @description Unix timestamp when the status was recorded
             * @example 1640995205
             */
            status_timestamp?: number;
            application?: components["schemas"]["ApplicationNode"];
            /**
             * @description State of the webhook update for this delivery status event
             * @example SUCCESS
             * @enum {string}
             */
            webhook_update_state?: "ERROR" | "SUCCESS";
            /**
             * Format: uri
             * @description URI of the webhook that received this delivery status update
             * @example https://example.com/webhook
             */
            webhook_uri?: string;
        };
        /**
         * @description Message delivery status
         * @example DELIVERED
         * @enum {string}
         */
        WhatsAppMessageDeliveryStatus: "ACCEPTED" | "DELIVERED" | "ERROR" | "READ" | "SENT";
        /** @description Meta application that processed the delivery status event */
        ApplicationNode: {
            /**
             * @description Unique identifier for the Meta application
             * @example 9876543210987654
             */
            id?: string;
            /**
             * @description Name of the Meta application
             * @example WhatsApp Business API Client
             */
            name?: string;
        };
        /** @description Paginated response containing message history events */
        MessageHistoryEventsResponse: {
            /** @description Array of message history event edges */
            data?: components["schemas"]["WhatsAppMessageHistoryEventsEdge"][];
            paging?: components["schemas"]["PaginationInfo"];
        };
        /** @description Pagination information for navigating through results */
        PaginationInfo: {
            /** @description Pagination cursors for navigation */
            cursors?: {
                /**
                 * @description Cursor for the previous page of results
                 * @example MAZDZD
                 */
                before?: string;
                /**
                 * @description Cursor for the next page of results
                 * @example MTAxNTExOTQ1MjAwNzI5NDE=
                 */
                after?: string;
            };
            /**
             * Format: uri
             * @description URL for the previous page of results
             * @example https://graph.facebook.com/v25.0/1234567890123456/events?before=MAZDZD
             */
            previous?: string;
            /**
             * Format: uri
             * @description URL for the next page of results
             * @example https://graph.facebook.com/v25.0/1234567890123456/events?after=MTAxNTExOTQ1MjAwNzI5NDE=
             */
            next?: string;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMessageHistoryEvents: {
        parameters: {
            query?: {
                /**
                 * @description Filter results by specific delivery status. When provided,
                 *     only events with this delivery status will be returned.
                 * @example DELIVERED
                 */
                delivery_status?: components["schemas"]["WhatsAppMessageDeliveryStatus"];
                /**
                 * @description Comma-separated list of fields to include in the response. If not specified,
                 *     default fields will be returned (cursor, node{id,delivery_status,occurrence_timestamp}).
                 *     Available fields: cursor, node{id,delivery_status,error_description,occurrence_timestamp,status_timestamp,application,webhook_update_state,webhook_uri}
                 * @example cursor,node{id,delivery_status,occurrence_timestamp,application}
                 */
                fields?: string;
                /**
                 * @description Maximum number of message history events to return per page.
                 *     Default is 25, maximum is 100.
                 * @example 25
                 */
                limit?: number;
                /**
                 * @description Cursor for pagination. Use this to get the next page of results.
                 *     This value comes from the `paging.cursors.after` field in previous responses.
                 * @example MTAxNTExOTQ1MjAwNzI5NDE=
                 */
                after?: string;
                /**
                 * @description Cursor for pagination. Use this to get the previous page of results.
                 *     This value comes from the `paging.cursors.before` field in previous responses.
                 * @example MAZDZD
                 */
                before?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business Message History ID. This ID is provided when you retrieve
                 *     message history and can be found through message history APIs.
                 * @example 1234567890123456
                 */
                "Message-History-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved WhatsApp message history events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageHistoryEventsResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter: delivery_status must be a valid delivery status",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to access message history events for this resource\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Message History ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "WhatsApp Business Message History not found\n",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "The requested fields are not available for this message history\n",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
