/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Pre-Verified-Phone-Number-ID}/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pre-Verified Phone Number Partners
         * @description Retrieve the list of partner businesses that have been granted access to a specific
         *     WhatsApp Business Pre-Verified Phone Number.
         *
         *     **Use Cases:**
         *     - Monitor partner business relationships and access permissions
         *     - Verify which businesses have access to shared pre-verified phone numbers
         *     - Retrieve partner business information for operational purposes
         *     - Validate partnership configurations before business operations
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         *
         *     **Caching:**
         *     Partner information can be cached for moderate periods, but partnership relationships
         *     may change. Implement appropriate cache invalidation strategies.
         */
        get: operations["getPreVerifiedPhoneNumberPartners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response containing partner businesses for a pre-verified phone number */
        WhatsAppBusinessPreVerifiedPhoneNumberPartnersResponse: {
            /** @description List of partner businesses with access to the pre-verified phone number */
            data: components["schemas"]["BusinessPartner"][];
            paging?: components["schemas"]["CursorPaging"];
        };
        /**
         * @description Business entity that has partner access to the pre-verified phone number.
         *     Returns standard Business node objects. Use the fields parameter to request
         *     additional Business node fields beyond the defaults.
         */
        BusinessPartner: {
            /**
             * @description Unique identifier for the partner business
             * @example 1234567890123456
             */
            id: string;
            /**
             * @description Name of the partner business
             * @example Partner Business Solutions Inc
             */
            name: string;
        };
        /** @description Cursor-based pagination information */
        CursorPaging: {
            cursors?: {
                /**
                 * @description Cursor pointing to the start of the page of data that has been returned
                 * @example MAZDZD
                 */
                before?: string;
                /**
                 * @description Cursor pointing to the end of the page of data that has been returned
                 * @example MTAxNTExOTQ1MjAwNzI5NDE=
                 */
                after?: string;
            };
            /**
             * @description Graph API endpoint URL for the next page of results
             * @example https://graph.facebook.com/v25.0/1234567890123456/partners?after=MTAxNTExOTQ1MjAwNzI5NDE%3D
             */
            next?: string;
            /**
             * @description Graph API endpoint URL for the previous page of results
             * @example https://graph.facebook.com/v25.0/1234567890123456/partners?before=MAZDZD
             */
            previous?: string;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPreVerifiedPhoneNumberPartners: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated list of Business node fields to include in the response. If not specified,
                 *     default fields will be returned (id, name).
                 * @example id,name
                 */
                fields?: string;
                /**
                 * @description Maximum number of partner businesses to return per page. Default is 25, maximum is 100.
                 * @example 50
                 */
                limit?: number;
                /**
                 * @description Cursor for pagination. Use the 'after' cursor from a previous response to get the next page.
                 * @example MTAxNTExOTQ1MjAwNzI5NDE=
                 */
                after?: string;
                /**
                 * @description Cursor for pagination. Use the 'before' cursor from a previous response to get the previous page.
                 * @example MAZDZD
                 */
                before?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your Pre-Verified Phone Number ID. This ID is provided when the pre-verified phone number
                 *     is created and can be found in your WhatsApp Business Account management interface.
                 * @example 1234567890123456
                 */
                "Pre-Verified-Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved partner businesses for the pre-verified phone number */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppBusinessPreVerifiedPhoneNumberPartnersResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter: pre_verified_phone_number_id must be a valid numeric string",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to access this Pre-Verified Phone Number\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Pre-Verified Phone Number ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Pre-Verified Phone Number not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "The requested fields are not available for this pre-verified phone number\n",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
