/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{WABA-ID}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get WhatsApp Business Account Activities
         * @description Retrieve activity history for a WhatsApp Business Account.
         *     Default fields returned: event_type, timestamp.
         */
        get: operations["getWhatsAppBusinessAccountActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description WhatsApp Business Account activity history record */
        WhatsAppBusinessActivityHistory: {
            /**
             * @description Unique identifier for the activity record
             * @example 1234567890123456
             */
            id?: string;
            /**
             * @description ID of the business that performed the activity
             * @example 9876543210987654
             */
            actor_business_id?: string;
            /**
             * @description ID of the user or system that performed the activity
             * @example 5678901234567890
             */
            actor_id?: string;
            category?: components["schemas"]["WhatsAppBusinessAccountHistoryComponentType"];
            event_type?: components["schemas"]["WhatsAppBusinessAccountHistoryEventType"];
            /**
             * Format: int64
             * @description Unix timestamp when the activity occurred
             * @example 1697377800
             */
            timestamp?: number;
        };
        /**
         * @description Category of the activity
         * @example PHONE_NUMBER
         * @enum {string}
         */
        WhatsAppBusinessAccountHistoryComponentType: "ACCOUNT" | "APP" | "BILLING" | "BUSINESS_PROFILE" | "MESSAGE_TEMPLATE" | "PAYMENT_CONFIGURATION" | "PHONE_NUMBER" | "USER" | "WHATSAPP_BUSINESS_PAYMENT_TOS";
        /**
         * @description Specific event type of the activity
         * @example PHONE_NUMBER_ADDED
         * @enum {string}
         */
        WhatsAppBusinessAccountHistoryEventType: "ACCOUNT_MIGRATED_FROM_OBO_TO_SHARED" | "ACCOUNT_MIGRATION_FROM_OBO_TO_SHARED_INTENT\n" | "ACCOUNT_REVIEW_STATUS_UPDATED" | "ACCOUNT_SANDBOX_ELIGIBLE" | "ACCOUNT_VERIFIED" | "APP_INSTALLED" | "APP_UNINSTALLED" | "BILLING_ADDED" | "BILLING_DELETED" | "BILLING_UPDATED" | "BOT_CREATED" | "BOT_UPDATED" | "BUSINESS_CAPABILITY_UPDATED" | "BUSINESS_PRIMARY_LOCATION_COUNTRY_UPDATED\n" | "BUSINESS_PROFILE_PICTURE_UPDATED" | "BUSINESS_PROFILE_UPDATED" | "CALLING_CONFIG_CHANGED" | "CALLING_STATUS_CHANGED" | "DATA_LOCALIZATION_SETTING_CHANGED" | "DEFAULT" | "MESSAGE_TEMPLATE_ADDED" | "MESSAGE_TEMPLATE_DELETED" | "MESSAGE_TEMPLATE_EDITED" | "NAME_REVERFICATION_REQUESTED" | "OFFICIAL_BUSINESS_ACCOUNT_REQUEST" | "OTP_REQUESTED" | "OTP_VERIFIED" | "PARTNER_ADDED" | "PARTNER_REMOVED" | "PAYMENT_CONFIGURATION_UPDATED" | "PHONE_MIGRATION_COMPLETED" | "PHONE_MIGRATION_STARTED" | "PHONE_NUMBER_ADDED" | "PHONE_NUMBER_DELETED" | "PHONE_NUMBER_DEREGISTERED_FROM_CLOUD_API" | "PHONE_NUMBER_OBA_APPROVED" | "PHONE_NUMBER_REGISTERED_ON_CLOUD_API" | "SEARCH_STATUS_CHANGED_TO_NON_VISIBLE" | "SEARCH_STATUS_CHANGED_TO_PENDING_VISIBLE" | "SEARCH_STATUS_CHANGED_TO_VISIBLE" | "TWO_STEP_VERIFICATION_PIN_CHANGED" | "TWO_STEP_VERIFICATION_PIN_REMOVED" | "TWO_STEP_VERIFICATION_PIN_RESET_REQUESTED\n" | "USER_ADDED" | "USER_DELETED" | "USER_PERMISSION_ADDED" | "USER_PERMISSION_UPDATED" | "WELCOME_MESSAGE_SEQUENCE_ADDED" | "WELCOME_MESSAGE_SEQUENCE_DELETED" | "WELCOME_MESSAGE_SEQUENCE_UPDATED" | "WHATSAPP_BUSINESS_PAYMENT_TOS_ACCEPTED";
        /** @description Paginated list of WhatsApp Business Account activities */
        ActivityList: {
            /** @description Array of activity records */
            data: components["schemas"]["WhatsAppBusinessActivityHistory"][];
            paging?: components["schemas"]["Paging"];
        };
        /** @description Pagination information for activity results */
        Paging: {
            cursors?: {
                /**
                 * @description Cursor pointing to the start of the page of data
                 * @example MTAxNTExOTQ1MjAwNzI5NDE=
                 */
                before?: string;
                /**
                 * @description Cursor pointing to the end of the page of data
                 * @example NDMyNzQyODI3OTQw
                 */
                after?: string;
            };
            /** @description Graph API endpoint URL for the previous page of results */
            previous?: string;
            /** @description Graph API endpoint URL for the next page of results */
            next?: string;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWhatsAppBusinessAccountActivities: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated list of fields to include in the response.
                 *     Default fields: event_type, timestamp.
                 *     Available fields: id, actor_business_id, actor_id, category, event_type, timestamp
                 * @example id,category,event_type,timestamp,actor_id
                 */
                fields?: string;
                /**
                 * @description Maximum number of activity records to return per page
                 * @example 50
                 */
                limit?: number;
                /** @description Cursor for pagination */
                after?: string;
                /** @description Cursor for pagination */
                before?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description WhatsApp Business Account ID
                 * @example 1234567890123456
                 */
                "WABA-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved WhatsApp Business Account activities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityList"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to access this resource\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
