/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Business-ID}/share_preverified_numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Share Pre-Verified Phone Number with Another Business
         * @description Share a pre-verified phone number with another business entity, granting specified
         *     permissions for collaborative WhatsApp Business messaging operations.
         *
         *     **Use Cases:**
         *     - Enable partner businesses to use your pre-verified phone numbers for messaging
         *     - Share phone number resources between parent and subsidiary businesses
         *     - Facilitate multi-business WhatsApp integrations with shared phone number access
         *     - Establish temporary or permanent phone number sharing relationships
         *
         *     **Business Logic:**
         *     - Only businesses with appropriate ownership or sharing rights can share phone numbers
         *     - Shared phone numbers maintain original ownership while granting usage permissions
         *     - Multiple businesses can have access to the same phone number with different permission levels
         *     - Sharing relationships can be time-limited with automatic expiration
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         *
         *     **Validation:**
         *     - Pre-verified phone number must exist and be accessible to the requesting business
         *     - Target business must be a valid and accessible business entity
         *     - Requested permissions must be valid and within the scope of allowed sharing permissions
         *     - Sharing operation must comply with business relationship and access control policies
         */
        post: operations["sharePreVerifiedPhoneNumber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request payload for sharing a pre-verified phone number with another business */
        PreVerifiedPhoneNumberShareRequest: {
            /**
             * @description Unique identifier of the pre-verified phone number to be shared.
             *     Must be a valid phone number ID that the requesting business owns or has sharing rights to.
             * @example 1234567890123456
             */
            preverified_id: string;
            /**
             * @description Business ID of the partner business that will receive access to the pre-verified phone number.
             *     Must be a valid business entity accessible to the requesting app.
             * @example 9876543210987654
             */
            partner_business_id: string;
        };
        /** @description Response containing details of the successful phone number sharing operation */
        PreVerifiedPhoneNumberShareResponse: {
            /**
             * @description Indicates whether the sharing operation was successful
             * @example true
             */
            success: boolean;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sharePreVerifiedPhoneNumber: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your Business ID that owns or has sharing rights to the pre-verified phone number.
                 *     This ID can be found in your Meta Business Manager or through business management APIs.
                 * @example 1234567890123456
                 */
                "Business-ID": string;
            };
            cookie?: never;
        };
        /** @description Phone number sharing configuration and target business details */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreVerifiedPhoneNumberShareRequest"];
            };
        };
        responses: {
            /** @description Successfully shared pre-verified phone number with target business */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreVerifiedPhoneNumberShareResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Resource does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
