/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Phone-Number-ID}/whatsapp_business_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get WhatsApp Business Profile
         * @description Retrieve comprehensive information about a WhatsApp Business Profile, including
         *     business details, contact information, and profile settings.
         *
         *
         *     **Use Cases:**
         *     - Retrieve current business profile information
         *     - Check business contact details and settings
         *     - Verify business vertical and website information
         *     - Get profile picture URL and about section
         *
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         *
         *
         *     **Caching:**
         *     Business profile information can be cached for moderate periods, but should be
         *     refreshed periodically to ensure accuracy.
         */
        get: operations["getWhatsAppBusinessProfile"];
        put?: never;
        /**
         * Update WhatsApp Business Profile
         * @description Update WhatsApp Business Profile information including business details,
         *     contact information, and profile settings.
         *
         *
         *     **Use Cases:**
         *     - Update business description and contact information
         *     - Modify business address and website information
         *     - Change business vertical classification
         *     - Update profile picture using Resumable Upload API
         *     - Update profile picture and about section
         *
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         *
         *
         *     **Profile Picture Updates:**
         *     To update the profile picture, first use the Resumable Upload API to obtain a
         *     profile_picture_handle, then include it in the request.
         */
        post: operations["updateWhatsAppBusinessProfileInformation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description WhatsApp Business Profile information and settings */
        WhatsAppBusinessProfile: {
            /**
             * @description The messaging service used for the request
             * @example whatsapp
             * @enum {string}
             */
            messaging_product: "whatsapp";
            /**
             * @description The text to display in business profile's About section
             * @example Welcome to our business! We provide excellent service.
             */
            about?: string;
            /**
             * @description The address of the business
             * @example 123 Business Street, City, State 12345
             */
            address?: string;
            /**
             * @description Description of the business
             * @example We are a leading provider of quality products and services.
             */
            description?: string;
            /**
             * Format: email
             * @description The contact email address of the business
             * @example contact@business.com
             */
            email?: string;
            /**
             * Format: uri
             * @description URL of the business profile picture
             * @example https://pps.whatsapp.net/v/profile_picture_url
             */
            profile_picture_url?: string;
            /**
             * @description URLs associated with the business
             * @example {
             *       "0": "https://www.business.com",
             *       "1": "https://www.facebook.com/business"
             *     }
             */
            websites?: string[];
            vertical?: components["schemas"]["WhatsAppBusinessVertical"];
        };
        /** @description Request payload for updating WhatsApp Business Profile */
        WhatsAppBusinessProfileUpdateRequest: {
            /**
             * @description The messaging service used for the request
             * @example whatsapp
             * @enum {string}
             */
            messaging_product: "whatsapp";
            /**
             * @description The text to display in business profile's About section
             * @example Welcome to our business! We provide excellent service.
             */
            about?: string;
            /**
             * @description The address of the business
             * @example 123 Business Street, City, State 12345
             */
            address?: string;
            /**
             * @description Description of the business
             * @example We are a leading provider of quality products and services.
             */
            description?: string;
            /**
             * Format: email
             * @description The contact email address of the business
             * @example contact@business.com
             */
            email?: string;
            /**
             * @description The handle of the profile picture generated from Resumable Upload API
             * @example 4:VGVzdC5wbmc=:aW1hZ2UvanBlZw==:ARat4Mt-L09JON3f30SmDkdyPSuyBkDDYiB4TFXuXISjdgHoNp2b7j882_9Jzr2tPrdKxi92UygyVzTivJiOvmebMpZ6MIjTik3gTyI3ZCQAgQ:e:1659995302:2022308451254161:636685196:ARZf1ftR5N6-qSLtklU
             */
            profile_picture_handle?: string;
            /**
             * @description URLs associated with the business
             * @example {
             *       "0": "https://www.business.com",
             *       "1": "https://www.facebook.com/business"
             *     }
             */
            websites?: string[];
            vertical?: components["schemas"]["WhatsAppBusinessVertical"];
        };
        /**
         * @description The industry type of the business
         * @example RESTAURANT
         * @enum {string}
         */
        WhatsAppBusinessVertical: "OTHER" | "AUTO" | "BEAUTY" | "APPAREL" | "EDU" | "ENTERTAIN" | "EVENT_PLAN" | "FINANCE" | "GROCERY" | "GOVT" | "HOTEL" | "HEALTH" | "NONPROFIT" | "PROF_SERVICES" | "RETAIL" | "TRAVEL" | "RESTAURANT" | "ALCOHOL" | "ONLINE_GAMBLING" | "PHYSICAL_GAMBLING" | "OTC_DRUGS";
        /** @description Response containing business profile information */
        WhatsAppBusinessProfileResponse: {
            /**
             * @example {
             *       "0": {
             *         "business_profile": {
             *           "messaging_product": "whatsapp",
             *           "about": "Welcome to our business! We provide excellent service.\n",
             *           "address": "123 Business Street, City, State 12345",
             *           "description": "We are a leading provider of quality products and services.\n",
             *           "email": "contact@business.com",
             *           "profile_picture_url": "https://pps.whatsapp.net/v/profile_picture_url\n",
             *           "websites": {
             *             "0": "https://www.business.com",
             *             "1": "https://www.facebook.com/business"
             *           },
             *           "vertical": "RESTAURANT"
             *         }
             *       }
             *     }
             */
            data?: {
                business_profile?: components["schemas"]["WhatsAppBusinessProfile"];
            }[];
        };
        /** @description Response after updating business profile */
        WhatsAppBusinessProfileUpdateResponse: {
            /**
             * @description Indicates whether the update was successful
             * @example true
             */
            success?: boolean;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWhatsAppBusinessProfile: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated list of fields to include in the response. If not specified,
                 *     default fields will be returned (messaging_product, about, address, description, email, profile_picture_url, websites, vertical).
                 *     Available fields: messaging_product, about, address, description, email, profile_picture_url, websites, vertical
                 * @example messaging_product,about,address,description,email,websites,vertical
                 */
                fields?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v23.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business phone number ID. This ID represents the phone number
                 *     status entity and can be obtained from your WhatsApp Business Account phone numbers list.
                 * @example 1234567890123456
                 */
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved WhatsApp Business Profile information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppBusinessProfileResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter: phone_number_id must be a valid numeric string",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to access this WhatsApp Business Profile\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Phone Number ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "WhatsApp Business Profile not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "The requested fields are not available for this profile\n",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Too Many Requests - Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Application request limit reached",
                     *         "type": "OAuthException",
                     *         "code": 4,
                     *         "error_subcode": 2446079,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
    updateWhatsAppBusinessProfileInformation: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v23.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business phone number ID. This ID represents the phone number
                 *     status entity and can be obtained from your WhatsApp Business Account phone numbers list.
                 * @example 1234567890123456
                 */
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatsAppBusinessProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successfully updated WhatsApp Business Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppBusinessProfileUpdateResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter: email must be a valid email address",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to modify this WhatsApp Business Profile\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Phone Number ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "WhatsApp Business Profile not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "The profile picture handle is invalid or expired\n",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Too Many Requests - Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Application request limit reached",
                     *         "type": "OAuthException",
                     *         "code": 4,
                     *         "error_subcode": 2446079,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
