/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Business-ID}/preverified_numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pre-Verified Phone Numbers
         * @description Retrieve pre-verified phone numbers available for use with the specified business.
         *     This endpoint provides information about phone numbers that have been pre-verified
         *     and are ready for use with WhatsApp Business messaging operations.
         *
         *     **Use Cases:**
         *     - Retrieve available pre-verified phone numbers for business messaging setup
         *     - Check verification status of phone numbers
         *     - Monitor pre-verified phone number inventory
         *     - Facilitate quick business messaging setup with pre-verified numbers
         *
         *     **Filtering:**
         *     - Results can be filtered by phone_number or code_verification_status
         *     - Cursor-based pagination is supported for large result sets
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         */
        get: operations["getPreVerifiedPhoneNumbers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Pre-verified phone number node fields */
        PreVerifiedPhoneNumber: {
            /**
             * @description Unique identifier for the pre-verified phone number
             * @example 1234567890123456
             */
            id: string;
            code_verification_status?: components["schemas"]["WhatsAppCodeVerificationStatus"];
            /**
             * Format: int64
             * @description Unix timestamp when the verification code was last verified
             * @example 1705312200
             */
            code_verification_time?: number;
            /** @description Business that owns this pre-verified phone number */
            owner_business?: {
                /**
                 * @description Unique identifier for the business
                 * @example 9876543210987654
                 */
                id?: string;
                /**
                 * @description Name of the business
                 * @example Example Business Corp
                 */
                name?: string;
            };
            /**
             * @description The phone number in E.164 format
             * @example +15551234567
             */
            phone_number?: string;
            /**
             * Format: int64
             * @description Unix timestamp when the verification expires
             * @example 1705398600
             */
            verification_expiry_time?: number;
        };
        /**
         * @description Current verification status of the pre-verified phone number
         * @example VERIFIED
         * @enum {string}
         */
        WhatsAppCodeVerificationStatus: "EXPIRED" | "NOT_VERIFIED" | "VERIFIED";
        /** @description Response containing list of pre-verified phone numbers */
        PreVerifiedPhoneNumbersResponse: {
            /** @description List of pre-verified phone numbers */
            data: components["schemas"]["PreVerifiedPhoneNumber"][];
            paging?: components["schemas"]["CursorPaging"];
        };
        /** @description Cursor-based pagination information */
        CursorPaging: {
            cursors?: {
                /**
                 * @description Cursor pointing to the start of the page of data that has been returned
                 * @example QVFIUmx1WTBpMGpJWXprYzVYaVhabW9PVks4ZD0
                 */
                before?: string;
                /**
                 * @description Cursor pointing to the end of the page of data that has been returned
                 * @example QVFIUjJ5WjBpMGpJWXprYzVYaVhabW9PVks4ZD0
                 */
                after?: string;
            };
            /**
             * @description Graph API endpoint URL for the next page of results
             * @example https://graph.facebook.com/v25.0/1234567890123456/preverified_numbers?after=QVFIUjJ5WjBpMGpJWXprYzVYaVhabW9PVks4ZD0
             */
            next?: string;
            /**
             * @description Graph API endpoint URL for the previous page of results
             * @example https://graph.facebook.com/v25.0/1234567890123456/preverified_numbers?before=QVFIUmx1WTBpMGpJWXprYzVYaVhabW9PVks4ZD0
             */
            previous?: string;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPreVerifiedPhoneNumbers: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated list of fields to include in the response.
                 *     Available fields: id, code_verification_status, code_verification_time,
                 *     owner_business, phone_number, verification_expiry_time
                 * @example id,phone_number,code_verification_status
                 */
                fields?: string;
                /**
                 * @description Filter results by phone number. Only pre-verified numbers matching the
                 *     specified phone number will be returned.
                 * @example +15551234567
                 */
                phone_number?: string;
                /**
                 * @description Filter results by code verification status. Only phone numbers with the
                 *     specified verification status will be returned.
                 * @example VERIFIED
                 */
                code_verification_status?: components["schemas"]["WhatsAppCodeVerificationStatus"];
                /**
                 * @description Maximum number of phone numbers to return per page.
                 * @example 25
                 */
                limit?: number;
                /**
                 * @description Cursor for pagination. Use this to retrieve the next page of results.
                 *     This value is provided in the 'paging' object of previous responses.
                 * @example QVFIUjJ5WjBpMGpJWXprYzVYaVhabW9PVks4ZD0
                 */
                after?: string;
                /**
                 * @description Cursor for pagination. Use this to retrieve the previous page of results.
                 *     This value is provided in the 'paging' object of previous responses.
                 * @example QVFIUmx1WTBpMGpJWXprYzVYaVhabW9PVks4ZD0
                 */
                before?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your Business ID for which to retrieve pre-verified phone numbers.
                 *     This ID can be found in your Meta Business Manager or through business management APIs.
                 * @example 1234567890123456
                 */
                "Business-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved pre-verified phone numbers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreVerifiedPhoneNumbersResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to access pre-verified phone numbers for this business\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Business does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Business not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
