/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Pre-Verified-Phone-Number-ID}/verify_code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify OTP Code for Pre-Verified Phone Number
         * @description Verify the OTP code received for a pre-verified phone number to complete the
         *     verification process. This endpoint validates the code and updates the verification
         *     status of the phone number.
         *
         *     **Use Cases:**
         *     - Complete phone number verification during WhatsApp Business onboarding
         *     - Verify ownership of phone numbers for business messaging
         *     - Enable phone numbers for WhatsApp Business API usage
         *
         *     **Rate Limiting:**
         *     This endpoint has specific rate limits to prevent abuse:
         *     - 125 requests per hour for business use cases
         *     - Standard Graph API rate limits also apply
         *
         *     **Code Validation:**
         *     - Codes are time-sensitive and expire after a set period
         *     - Each code can only be used once
         *     - Invalid or expired codes will result in verification failure
         *
         *     **Error Handling:**
         *     - Invalid codes return 400 Bad Request
         *     - Expired codes return 422 Unprocessable Entity
         *           operationId: verifyPreVerifiedPhoneNumberCode
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The user agent string identifying the client software making the request. */
                    "User-Agent"?: string;
                    /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                    Authorization: string;
                };
                path: {
                    /**
                     * @description Graph API version to use for this request. Determines the API behavior and available features.
                     * @example v25.0
                     */
                    Version: string;
                    /**
                     * @description Your Pre-Verified Phone Number ID. This ID is provided when you create the pre-verified
                     *     phone number and can be found in your WhatsApp Business Manager or through phone number APIs.
                     * @example 1234567890123456
                     */
                    "Pre-Verified-Phone-Number-ID": string;
                };
                cookie?: never;
            };
            /** @description Verification code details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyCodeRequest"];
                };
            };
            responses: {
                /** @description Successfully verified the OTP code */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VerifyCodeResponse"];
                    };
                };
                /** @description Bad Request - Invalid parameters or malformed request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphAPIError"];
                    };
                };
                /** @description Unauthorized - Invalid or missing access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "message": "Invalid OAuth access token",
                         *         "type": "OAuthException",
                         *         "code": 190,
                         *         "error_subcode": 463,
                         *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["GraphAPIError"];
                    };
                };
                /** @description Forbidden - Insufficient permissions or access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "message": "Your app doesn't have permission to access this Pre-Verified Phone Number\n",
                         *         "type": "OAuthException",
                         *         "code": 200,
                         *         "error_subcode": 1349174,
                         *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                         *         "error_user_title": "Permission Denied",
                         *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["GraphAPIError"];
                    };
                };
                /** @description Not Found - Pre-Verified Phone Number ID does not exist or is not accessible */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "message": "Pre-Verified Phone Number not found",
                         *         "type": "GraphMethodException",
                         *         "code": 803,
                         *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["GraphAPIError"];
                    };
                };
                /** @description Unprocessable Entity - Code is invalid, expired, or already used */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphAPIError"];
                    };
                };
                /** @description Internal Server Error - Unexpected server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "message": "An unexpected error occurred. Please retry your request\n",
                         *         "type": "GraphMethodException",
                         *         "code": 2,
                         *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                         *         "is_transient": true
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["GraphAPIError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request payload for verifying OTP code */
        VerifyCodeRequest: {
            /**
             * @description The numeric verification code received via SMS or voice call.
             *     This code is provided after calling the request_code endpoint.
             * @example 123456
             */
            code: string;
        };
        /** @description Response indicating successful code verification */
        VerifyCodeResponse: {
            /**
             * @description Indicates whether the code verification was successful
             * @example true
             */
            success: boolean;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid verification code
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Verification Failed
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example The verification code you entered is invalid or has expired
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
