/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Pre-Verified-Phone-Number-ID}/request_code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Verification Code for Pre-Verified Phone Number
         * @description Request a verification code for a pre-verified phone number via SMS or voice call.
         *     This is part of the WhatsApp Business Account onboarding process where pre-approved
         *     phone numbers must be verified before they can be used for messaging.
         *
         *     **Process Flow:**
         *     1. Call this endpoint to request a verification code
         *     2. User receives code via SMS or voice call
         *     3. Use the verify_code endpoint to complete verification
         *     4. Phone number becomes active for messaging
         *
         *     **Rate Limiting:**
         *     - Limited number of code requests per phone number per time period
         *     - Exponential backoff recommended for retry attempts
         *     - Voice calls may have additional restrictions
         *
         *     **Language Support:**
         *     Verification messages are sent in the specified language when available.
         *     Falls back to English (en_US) if the requested language is not supported.
         *
         *     **Security Considerations:**
         *     - Codes expire after a short time period
         *     - Limited number of verification attempts allowed
         *     - Phone number must be pre-verified and owned by requesting business
         */
        post: operations["requestPreVerifiedPhoneNumberCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for requesting verification code */
        RequestCodeRequest: {
            code_method: components["schemas"]["PhoneVerificationMethodCode"];
            /**
             * @description Language/locale code for the verification message. Must be a valid locale identifier.
             *     The verification message will be sent in this language if supported.
             *     Supports various formats including xx_XX, xx-XX, and extended locale codes.
             * @example en_US
             */
            language: string;
        };
        /**
         * @description Method for receiving the verification code
         * @example SMS
         * @enum {string}
         */
        PhoneVerificationMethodCode: "IVR" | "SMS" | "VOICE";
        /** @description Response after successfully requesting verification code */
        RequestCodeResponse: {
            /**
             * @description Indicates whether the verification code request was successful
             * @example true
             */
            success: boolean;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestPreVerifiedPhoneNumberCode: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your pre-verified phone number ID. This ID is provided when the phone number
                 *     is pre-verified and can be found in your WhatsApp Business Account settings.
                 * @example 1234567890123456
                 */
                "Pre-Verified-Phone-Number-ID": string;
            };
            cookie?: never;
        };
        /** @description Verification code request parameters */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeRequest"];
            };
        };
        responses: {
            /** @description Successfully requested verification code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Pre-verified phone number ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Pre-verified phone number not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
