/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Phone-Number-ID}/conversational_automation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure Conversational Automation
         * @description Configure conversational automation settings for a WhatsApp Business Account phone number,
         *     including welcome messages, conversation prompts (ice breakers), and bot commands.
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         *
         *
         *     **Validation:**
         *     - Command names must be unique within the same phone number
         *     - Prompts and command descriptions must comply with WhatsApp Business policies
         *     - Maximum limits are enforced for prompts and commands
         */
        post: operations["configureConversationalAutomation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request payload for configuring conversational automation settings */
        ConversationalAutomationRequest: {
            /**
             * @description Whether to enable welcome messages for new conversations
             * @default false
             * @example true
             */
            enable_welcome_message: boolean;
            /**
             * @description List of conversation prompts (ice breakers) to help guide customer interactions
             * @default []
             * @example {
             *       "0": "How can I help you today?",
             *       "1": "What product are you interested in?",
             *       "2": "Do you need support?"
             *     }
             */
            prompts: string[];
            /**
             * @description List of bot commands for automated responses
             * @default []
             * @example {
             *       "0": {
             *         "command_name": "help",
             *         "command_description": "Get help with your order"
             *       },
             *       "1": {
             *         "command_name": "status",
             *         "command_description": "Check your order status"
             *       }
             *     }
             */
            commands: components["schemas"]["BotCommand"][];
        };
        /** @description Bot command configuration for automated responses */
        BotCommand: {
            /**
             * @description Name of the bot command (without leading slash)
             * @example help
             */
            command_name: string;
            /**
             * @description Description of what the command does
             * @example Get help with your order
             */
            command_description: string;
        };
        /** @description Response after successfully configuring conversational automation */
        ConversationalAutomationResponse: {
            /**
             * @description Indicates whether the automation configuration was successful
             * @example true
             */
            success: boolean;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    configureConversationalAutomation: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business phone number ID. This ID represents the phone number
                 *     entity and can be obtained from your WhatsApp Business Account phone numbers list.
                 * @example 1234567890123456
                 */
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationalAutomationRequest"];
            };
        };
        responses: {
            /** @description Successfully configured conversational automation settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationalAutomationResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to manage conversational automation for this phone number\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Phone number ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "WhatsApp Business phone number not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
