/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Phone-Number-ID}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                Version: string;
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message.
         * @description Send Message.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Common properties shared by all message types */
        BaseMessageProperties: {
            /** @example whatsapp */
            messaging_product: string;
            /**
             * @description The type of recipient.
             * @example individual
             * @enum {string}
             */
            recipient_type: "individual" | "group";
            /**
             * @description The recipient's phone number for individual messages, and group-id for group message.
             * @example 19505550005
             */
            to: string;
            /** @description The type of message */
            type: string;
            context?: components["schemas"]["MessageContext"];
        };
        /** @description Context information for replying to a message */
        MessageContext: {
            /**
             * @description The ID of the message to which this message is a reply.
             * @example wamid.gBGGSFcCNEOPAgkO_KJ55r4w_ww
             */
            message_id?: string;
        };
        /** @description A media object. Either `id` or `link` is required. */
        MediaObject: {
            /**
             * @description The media object ID. **Required when `link` is not used.**
             * @example MEDIA_OBJECT_ID
             */
            id: string;
            /** @description Optional caption for the media */
            caption?: string;
        } | {
            /**
             * Format: url
             * @description The protocol and URL of the media to be sent (HTTP/HTTPS only).
             * @example http(s)://example.com/media.mp4
             */
            link: string;
            /** @description Optional caption for the media */
            caption?: string;
        };
        Message: components["schemas"]["TextMessage"] | components["schemas"]["AudioMessage"] | components["schemas"]["DocumentMessage"] | components["schemas"]["ImageMessage"] | components["schemas"]["LocationMessage"] | components["schemas"]["VideoMessage"] | components["schemas"]["StickerMessage"] | components["schemas"]["ReactionMessage"] | components["schemas"]["InteractiveMessage"] | components["schemas"]["TemplateMessage"] | components["schemas"]["ContactsMessage"];
        TextMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "text";
            text: {
                /**
                 * @description The text of the message.
                 * @example Hello World!
                 */
                body?: string;
                preview_url?: boolean;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        AudioMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "audio";
            audio: components["schemas"]["MediaObject"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "audio";
        };
        VideoMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "video";
            video: components["schemas"]["MediaObject"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
        };
        DocumentMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "document";
            document: components["schemas"]["MediaObject"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document";
        };
        ImageMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "image";
            image: components["schemas"]["MediaObject"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
        };
        LocationMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "location";
            location: {
                /**
                 * @description The address of the location.
                 * @example 1 Hacker Way, Menlo Park, CA 94025
                 */
                address?: string;
                /**
                 * @description The latitude of the location.
                 * @example 37.4847
                 */
                latitude?: string;
                /**
                 * @description The longitude of the location.
                 * @example -122.1486
                 */
                longitude?: string;
                /**
                 * @description The name of the location.
                 * @example Meta HQ
                 */
                name?: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "location";
        };
        StickerMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "sticker";
            sticker: {
                /** @description The ID of the sticker. */
                id: string;
            } | {
                /** @description The URL of the sticker. */
                link: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sticker";
        };
        ReactionMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "reaction";
            reaction: {
                /** @description emoji */
                emoji?: string;
                /** @description reacted message-id */
                message_id?: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reaction";
        };
        InteractiveMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "interactive";
            interactive: components["schemas"]["InteractiveObject"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "interactive";
        };
        /** @description An object containing the content for an interactive message. */
        InteractiveObject: {
            /**
             * @description The type of interactive message to send.
             * @enum {string}
             */
            type: "button" | "call_permission_request" | "catalog_message" | "list" | "product" | "product_list" | "flow";
            header?: components["schemas"]["HeaderObject"];
            body?: components["schemas"]["BodyObject"];
            footer?: components["schemas"]["FooterObject"];
            action: components["schemas"]["ActionObject"];
        };
        /** @description Header content displayed on top of a message. Required for 'product_list' type. Cannot be set for 'product' type. */
        HeaderObject: {
            /**
             * @description The header type.
             * @enum {string}
             */
            type: "text" | "video" | "image" | "document";
            /** @description Text for the header. Required if 'type' is 'text'. Emojis supported, no markdown. */
            text?: string;
            /** @description Optional sub-text for the header. Emojis supported, no markdown. */
            sub_text?: string;
            /** @description Contains the media object for this document. Required if 'type' is 'document'. */
            document?: components["schemas"]["MediaObject"];
            /** @description Contains the media object for this image. Required if 'type' is 'image'. */
            image?: components["schemas"]["MediaObject"];
            /** @description Contains the media object for this video. Required if 'type' is 'video'. */
            video?: components["schemas"]["MediaObject"];
        };
        /** @description An object with the body of the message. Optional for 'product' type, required for other interactive message types. */
        BodyObject: {
            /** @description The content of the message body. Emojis and markdown are supported. */
            text: string;
        };
        /** @description An object with the footer of the message. Optional. */
        FooterObject: {
            /** @description The footer content. Emojis, markdown, and links are supported. */
            text: string;
        };
        /** @description Action you want the user to perform after reading the message. Its structure varies by interactive message type. */
        ActionObject: {
            /** @description Button content for List Messages. Cannot be empty, must be unique. Emojis supported, no markdown. */
            button: string;
            /** @description Array of section objects. */
            sections: components["schemas"]["SectionObject"][];
        } | {
            /** @description Array of button objects. */
            buttons: {
                /**
                 * @description Only supported type is "reply" for Reply Button.
                 * @enum {string}
                 */
                type: "reply";
                reply: {
                    /** @description Unique identifier for your button. No leading/trailing spaces. */
                    id: string;
                    /** @description Button title. Cannot be empty, must be unique. Emojis supported, no markdown. */
                    title: string;
                };
            }[];
        } | {
            /** @description Unique identifier of the Facebook catalog linked to your WhatsApp Business Account. */
            catalog_id: string;
            /** @description Unique identifier of the product in a catalog. Required for Single Product Messages. */
            product_retailer_id?: string;
            /** @description Array of section objects. */
            sections?: components["schemas"]["SectionObject"][];
        } | {
            /** @enum {string} */
            name: "catalog_message";
            parameters: {
                /** @description Product retailer ID for the thumbnail. */
                thumbnail_product_retailer_id: string;
            };
        } | {
            /** @enum {string} */
            name: "flow";
            parameters: {
                /**
                 * @description Must be "3".
                 * @enum {string}
                 */
                flow_message_version: "3";
                /** @description Unique identifier of the Flow provided by WhatsApp. Required unless flow_name is set. Cannot be used with flow_name. */
                flow_id?: string;
                /** @description The name of the Flow that you created. Required unless flow_id is set. Cannot be used with flow_id. */
                flow_name?: string;
                /** @description Text on the CTA button (e.g., "Signup"). Advised 30 characters or less, no emoji. */
                flow_cta: string;
                /**
                 * @description The current mode of the Flow, either "draft" or "published".
                 * @default published
                 * @enum {string}
                 */
                mode?: "draft" | "published";
                /** @description A token generated by the business to serve as an identifier. Defaults to "unused". */
                flow_token?: string;
                /**
                 * @description Either "navigate" to predefine the first screen, or "data_exchange" for advanced use cases.
                 * @default navigate
                 * @enum {string}
                 */
                flow_action?: "navigate" | "data_exchange";
                /** @description Optional only if 'flow_action' is 'navigate'. */
                flow_action_payload?: {
                    /**
                     * @description The 'id' of the first screen of the Flow.
                     * @default FIRST_ENTRY_SCREEN
                     */
                    screen?: string;
                    /** @description The input data for the first screen of the Flow. Must be a non-empty object. */
                    data?: Record<string, never>;
                };
            } & (unknown | unknown);
        } | {
            /** @enum {string} */
            name: "call_permission_request";
        };
        /** @description A section object, used in List Messages and Multi-Product Messages. */
        SectionObject: {
            /** @description Title of the section. Required if the message has more than one section. Max 24 characters. */
            title?: string;
            /** @description Array of product objects. */
            product_items?: {
                /** @description Unique identifier of the product in a catalog. */
                product_retailer_id: string;
            }[];
            /** @description Contains a list of rows. */
            rows?: {
                /** @description Unique row identifier. */
                id: string;
                /** @description Row title. */
                title: string;
                /** @description Optional row description. */
                description?: string;
            }[];
        };
        TemplateMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "template";
            /** @description Template content for the send request. `template.components` is where you provide header, body, and button parameter values for templates that define placeholders or variable buttons. */
            template: {
                /**
                 * @description Name of the approved message template to send.
                 * @example TEMPLATE_NAME
                 */
                name: string;
                /** @description Language in which the template should be rendered. */
                language: string;
                /**
                 * @description Optional list of template components that supply parameter values for variable parts of the template. Add a `header` component for header parameters, a `body` component for body placeholders, and a `button` component for button parameters when the template defines them.
                 * @example {
                 *       "0": {
                 *         "type": "header",
                 *         "parameters": {
                 *           "0": {
                 *             "type": "image",
                 *             "image": {
                 *               "link": "http(s)://example.com/image.jpg"
                 *             }
                 *           }
                 *         }
                 *       },
                 *       "1": {
                 *         "type": "body",
                 *         "parameters": {
                 *           "0": {
                 *             "type": "text",
                 *             "text": "Hello {{1}}! Your order of {{2}} is confirmed for {{3}}."
                 *           }
                 *         }
                 *       },
                 *       "2": {
                 *         "type": "button",
                 *         "sub_type": "quick_reply",
                 *         "index": "0",
                 *         "parameters": {
                 *           "0": {
                 *             "type": "payload",
                 *             "payload": "ORDER_DETAILS_CLICKED"
                 *           }
                 *         }
                 *       }
                 *     }
                 */
                components?: {
                    /** @enum {string} */
                    type: "header" | "body" | "button";
                    /** @enum {string} */
                    sub_type?: "quick_reply" | "url" | "copy_code";
                    index?: string;
                    parameters?: {
                        /** @enum {string} */
                        type: "text" | "currency" | "date_time" | "image" | "document" | "video" | "payload" | "coupon_code";
                        text?: string;
                        payload?: string;
                        coupon_code?: string;
                        image?: components["schemas"]["MediaObject"];
                        document?: components["schemas"]["MediaObject"];
                        video?: components["schemas"]["MediaObject"];
                        currency?: {
                            fallback_value?: string;
                            code?: string;
                            amount_1000?: number;
                        };
                        date_time?: {
                            fallback_value?: string;
                        };
                    }[];
                }[];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "template";
        };
        ContactsMessage: components["schemas"]["BaseMessageProperties"] & {
            /** @enum {string} */
            type?: "contacts";
            contacts: components["schemas"]["ContactObject"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "contacts";
        };
        ContactObject: {
            /** @description Full contact address(es) */
            addresses?: components["schemas"]["AddressObject"][];
            /**
             * Format: date
             * @description Date of birth (YYYY-MM-DD format)
             * @example 2012-08-18
             */
            birthday?: string;
            /** @description Contact email address(es) */
            emails?: components["schemas"]["EmailObject"][];
            /** @description Contact name object */
            name?: components["schemas"]["NameObject"];
            /** @description Contact organization information */
            org?: components["schemas"]["OrganizationObject"];
            /** @description Contact phone number(s) */
            phones?: components["schemas"]["PhoneObject"][];
            /** @description Contact URL(s) */
            urls?: components["schemas"]["UrlObject"][];
        };
        AddressObject: {
            /**
             * @description City name
             * @example Menlo Park
             */
            city?: string;
            /**
             * @description Full country name
             * @example United States
             */
            country?: string;
            /**
             * @description Two-letter ISO country code
             * @example us
             */
            country_code?: string;
            /**
             * @description State abbreviation
             * @example CA
             */
            state?: string;
            /**
             * @description Street address
             * @example 1 Hacker Way
             */
            street?: string;
            /**
             * @description Address type
             * @enum {string}
             */
            type?: "HOME" | "WORK";
            /**
             * @description ZIP code
             * @example 94025
             */
            zip?: string;
        };
        EmailObject: {
            /**
             * Format: email
             * @description Email address
             * @example test@example.com
             */
            email: string;
            /**
             * @description Email type
             * @enum {string}
             */
            type?: "HOME" | "WORK";
        };
        NameObject: {
            /**
             * @description First name
             * @example John
             */
            first_name?: string;
            /**
             * @description Formatted full name
             * @example John Smith
             */
            formatted_name?: string;
            /**
             * @description Last name
             * @example Smith
             */
            last_name?: string;
            /**
             * @description Middle name
             * @example D.
             */
            middle_name?: string;
            /**
             * @description Name prefix
             * @example Dr
             */
            prefix?: string;
            /**
             * @description Name suffix
             * @example Jr
             */
            suffix?: string;
        };
        OrganizationObject: {
            /**
             * @description Company name
             * @example WhatsApp
             */
            company?: string;
            /**
             * @description Department name
             * @example Design
             */
            department?: string;
            /**
             * @description Job title
             * @example Manager
             */
            title?: string;
        };
        PhoneObject: {
            /**
             * @description Phone number
             * @example +1 (650) 555-1234
             */
            phone: string;
            /**
             * @description Phone type
             * @enum {string}
             */
            type?: "HOME" | "WORK";
            /**
             * @description WhatsApp ID
             * @example 16505551234
             */
            wa_id?: string;
        };
        UrlObject: {
            /**
             * @description URL type
             * @enum {string}
             */
            type?: "HOME" | "WORK";
            /**
             * Format: uri
             * @description URL
             * @example https://www.facebook.com
             */
            url: string;
        };
        MessageResponsePayload: {
            /**
             * @example {
             *       "0": {
             *         "input": "48XXXXXXXXX",
             *         "wa_id": "48XXXXXXXXX "
             *       }
             *     }
             */
            contacts?: {
                /** @example 48XXXXXXXXX */
                input?: string;
                /** @example 48XXXXXXXXX */
                wa_id?: string;
            }[];
            /**
             * @example {
             *       "0": {
             *         "id": "wamid.gBGGSFcCNEOPAgkO_KJ55r4w_ww",
             *         "message_status": "accepted"
             *       }
             *     }
             */
            messages?: {
                /** @example wamid.gBGGSFcCNEOPAgkO_KJ55r4w_ww */
                id?: string;
                /**
                 * @description The status of a WhatsApp message:
                 *     - `accepted`: The message has been accepted by WhatsApp and is being processed
                 *     - `held_for_quality_assessment`: The message is being held for quality assessment before delivery
                 *     - `paused`: The message delivery has been paused
                 * @enum {string}
                 */
                message_status?: "accepted" | "held_for_quality_assessment" | "paused";
            }[];
            /** @example whatsapp */
            messaging_product?: string;
        };
        MarkMessageRequestPayload: {
            /** @example wamid.234123 */
            message_id: string;
            /** @example whatsapp */
            messaging_product: string;
            /** @example read */
            status: string;
        };
        MarkMessageResponsePayload: {
            /** @example true */
            success?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description CORS policy allowing access from any origin */
        "Access-Control-Allow-Origin": string;
        /** @description Alternative service advertisement for HTTP/3 */
        "Alt-Svc": string;
        /** @description Cache control directives for the response */
        "Cache-Control": string;
        /** @description Connection management directive */
        Connection: string;
        /** @description Size of the response body in bytes */
        "Content-Length": string;
        /** @description Date and time when the response was generated */
        Date: string;
        /** @description Expiration date for cached responses */
        Expires: string;
        /** @description Legacy cache control directive */
        Pragma: string;
        /** @description HSTS header enforcing HTTPS connections */
        "Strict-Transport-Security": string;
        /** @description Headers that affect caching and content negotiation */
        Vary: string;
        /** @description Facebook connection quality metrics */
        "X-FB-Connection-Quality": string;
        /** @description Facebook debug information for troubleshooting */
        "X-FB-Debug": string;
        /** @description Facebook Graph API version used for the request */
        "facebook-api-version": string;
        /** @description Business use case usage metrics and rate limiting information */
        "x-business-use-case-usage": string;
        /** @description Unique identifier for the request for debugging purposes */
        "x-fb-request-id": string;
        /** @description Facebook internal revision number */
        "x-fb-rev": string;
        /** @description Facebook trace identifier for request tracking */
        "x-fb-trace-id": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sendMessage: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                Version: string;
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Message"];
            };
        };
        responses: {
            /** @description Send Test Message / Send Text Message / Send Reply to Text Message / Send Reply with Reaction Message / Send Image Message by ID / Send Reply to Image Message by ID / Send Image Message by URL / Send Reply to Image Message by URL / Send Audio Message by ID / Send Reply to Audio Message by ID / Send Audio Message By URL / Send Reply to Audio Message by URL / Send Document Message by ID / Send Reply to Document Message by ID / Send Document Message by URL / Send Reply to Document Message by URL / Send Sticker Message By ID / Send Reply to Sticker Message by ID / Send Sticker Message By URL / Send Reply to Sticker Message by URL / Send Video Message By ID / Send Reply to Video Message by ID / Send Video Message By URL / Send Reply to Video Message by URL / Send Contact Message / Send Reply to Contact Message / Send Location Messages / Send Reply to Location Message / Send Message Template Text / Send Message Template Media / Send Interactive Message Template / Send List Message / Send Reply to List Message / Send Reply Button / Send Single Product Message / Example response / Example response / Send Draft Flow by Name / Send Draft Flow by ID / Send Published Flow by Name / Send Published Flow by ID / Send Flow Template Message / Send typing indicator and read receipt / Send Sample Text message / Send Sample Shipping Confirmation Template / Send Sample Issue Resolution Template */
            200: {
                headers: {
                    /** @description CORS policy allowing access from any origin */
                    "Access-Control-Allow-Origin"?: string;
                    /** @description Alternative service advertisement for HTTP/3 */
                    "Alt-Svc"?: string;
                    /** @description Cache control directives for the response */
                    "Cache-Control"?: string;
                    /** @description Connection management directive */
                    Connection?: string;
                    /** @description Size of the response body in bytes */
                    "Content-Length"?: string;
                    /** @description Date and time when the response was generated */
                    Date?: string;
                    /** @description Expiration date for cached responses */
                    Expires?: string;
                    /** @description Legacy cache control directive */
                    Pragma?: string;
                    /** @description HSTS header enforcing HTTPS connections */
                    "Strict-Transport-Security"?: string;
                    /** @description Headers that affect caching and content negotiation */
                    Vary?: string;
                    /** @description Facebook connection quality metrics */
                    "X-FB-Connection-Quality"?: string;
                    /** @description Facebook debug information for troubleshooting */
                    "X-FB-Debug"?: string;
                    /** @description Facebook Graph API version used for the request */
                    "facebook-api-version"?: string;
                    /** @description Business use case usage metrics and rate limiting information */
                    "x-business-use-case-usage"?: string;
                    /** @description Unique identifier for the request for debugging purposes */
                    "x-fb-request-id"?: string;
                    /** @description Facebook internal revision number */
                    "x-fb-rev"?: string;
                    /** @description Facebook trace identifier for request tracking */
                    "x-fb-trace-id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponsePayload"];
                };
            };
        };
    };
}
