/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Phone-Number-ID}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get phone number settings
         * @description Retrieve current settings for a WhatsApp Business phone number.
         *     Returns calling settings, payload encryption settings, and data
         *     storage configurations.
         */
        get: operations["getPhoneNumberSettings"];
        put?: never;
        /**
         * Update phone number settings
         * @description Update various settings for a WhatsApp Business phone number.
         *     You can configure calling settings, user identity change settings,
         *     payload encryption, and data storage configurations.
         *     Only one feature setting can be specified per request.
         */
        post: operations["updatePhoneNumberSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CallingSettingsRequest: {
            calling: components["schemas"]["CallingSettings"];
        };
        CallingSettings: {
            /**
             * @description Enable or disable calling feature
             * @enum {string}
             */
            status: "enabled" | "disabled";
            /**
             * @description Control visibility of the call icon
             * @enum {string}
             */
            call_icon_visibility?: "visible" | "hidden";
            video?: components["schemas"]["VideoSettings"];
            sip?: components["schemas"]["SipSettings"];
            /**
             * @description SRTP key exchange protocol
             * @enum {string}
             */
            srtp_key_exchange_protocol?: "DTLS-SRTP" | "SDES-SRTP";
        };
        VideoSettings: {
            /**
             * @description Enable or disable video calling
             * @enum {string}
             */
            status: "enabled" | "disabled";
        };
        SipSettings: {
            /**
             * @description Enable or disable SIP calling
             * @enum {string}
             */
            status: "enabled" | "disabled";
        };
        UserIdentityChangeSettingsRequest: {
            user_identity_change: components["schemas"]["UserIdentityChangeSettings"];
        };
        UserIdentityChangeSettings: {
            /** @description Enable or disable user identity change notifications */
            enabled: boolean;
        };
        PayloadEncryptionSettingsRequest: {
            payload_encryption: components["schemas"]["PayloadEncryptionSettings"];
        };
        PayloadEncryptionSettings: {
            /**
             * @description Enable or disable payload encryption
             * @enum {string}
             */
            status: "enabled" | "disabled";
            /**
             * @description Base64-encoded public key for payload encryption
             *     (required when enabling encryption)
             */
            client_encryption_key?: string;
        };
        StorageConfigurationSettingsRequest: {
            storage_configuration: components["schemas"]["StorageConfigurationSettings"];
        };
        StorageConfigurationSettings: {
            /** @description Enable or disable custom storage configuration */
            enabled: boolean;
            /** @description Data storage region */
            region?: string;
        };
        PhoneNumberSettingsResponse: {
            calling: components["schemas"]["CallingSettingsResponse"];
            payload_encryption?: components["schemas"]["PayloadEncryptionSettingsResponse"];
            storage_configuration: components["schemas"]["StorageConfigurationSettingsResponse"];
        };
        CallingSettingsResponse: {
            /**
             * @description Current calling feature status
             * @enum {string}
             */
            status: "enabled" | "disabled";
            /**
             * @description Current call icon visibility setting
             * @enum {string}
             */
            call_icon_visibility: "visible" | "hidden";
            ip_addresses: {
                /** @description Default IP addresses for calling */
                default: string[];
            };
            /**
             * @description Callback permission status
             * @enum {string}
             */
            callback_permission_status: "enabled" | "disabled";
            /**
             * @description SRTP key exchange protocol (optional)
             * @enum {string}
             */
            srtp_key_exchange_protocol?: "DTLS-SRTP" | "SDES-SRTP";
            call_hours?: components["schemas"]["CallHoursSettings"];
            call_icons?: components["schemas"]["CallIconsSettings"];
            sip?: components["schemas"]["SipSettingsResponse"];
            video?: components["schemas"]["VideoSettingsResponse"];
            audio?: components["schemas"]["AudioSettingsResponse"];
            restrictions?: components["schemas"]["CallingRestrictionsResponse"];
        };
        CallHoursSettings: {
            /**
             * @description Call hours feature status
             * @enum {string}
             */
            status: "enabled" | "disabled";
            /** @description Timezone for call hours */
            timezone?: string;
            /** @description Start day of the week */
            day_of_week_start?: string;
        };
        CallIconsSettings: {
            /** @description List of countries where call icons are restricted */
            restrict_to_user_countries?: string[];
        };
        SipSettingsResponse: {
            /**
             * @description SIP calling status
             * @enum {string}
             */
            status: "enabled" | "disabled";
            /** @description SIP server configuration */
            servers?: components["schemas"]["SipServerInfo"][];
        };
        SipServerInfo: {
            /** @description Application ID for SIP server */
            app_id: string;
            /** @description SIP server hostname */
            hostname: string;
            /** @description SIP server port (optional) */
            port?: number;
            /** @description SIP password (only included when include_sip_credentials=true) */
            password?: string;
        };
        VideoSettingsResponse: {
            /**
             * @description Video calling status
             * @enum {string}
             */
            status: "enabled" | "disabled";
        };
        AudioSettingsResponse: {
            /**
             * @description Audio calling status
             * @enum {string}
             */
            status?: "enabled" | "disabled";
        };
        CallingRestrictionsResponse: {
            restrictions?: {
                /** @description Type of restriction */
                type?: string;
                /**
                 * Format: int64
                 * @description Expiration timestamp for the restriction
                 */
                expiration?: number;
            }[];
        };
        PayloadEncryptionSettingsResponse: {
            /**
             * @description Payload encryption status
             * @enum {string}
             */
            status: "enabled" | "disabled";
            /** @description Client encryption key fingerprint (when encryption is enabled) */
            client_encryption_key_fingerprint?: string;
            /** @description Cloud encryption key (when encryption is enabled) */
            cloud_encryption_key?: string;
        };
        StorageConfigurationSettingsResponse: {
            /**
             * @description Data storage configuration status
             * @enum {string}
             */
            status: "default" | "in_country_storage_enabled";
            /** @description Data localization region (when in-country storage is enabled) */
            data_localization_region?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description CORS policy allowing access from any origin */
        "Access-Control-Allow-Origin": string;
        /** @description Alternative service advertisement for HTTP/3 */
        "Alt-Svc": string;
        /** @description Cache control directives for the response */
        "Cache-Control": string;
        /** @description Connection management directive */
        Connection: string;
        /** @description Size of the response body in bytes */
        "Content-Length": string;
        /** @description Date and time when the response was generated */
        Date: string;
        /** @description Expiration date for cached responses */
        Expires: string;
        /** @description Legacy cache control directive */
        Pragma: string;
        /** @description HSTS header enforcing HTTPS connections */
        "Strict-Transport-Security": string;
        /** @description Headers that affect caching and content negotiation */
        Vary: string;
        /** @description Facebook connection quality metrics */
        "X-FB-Connection-Quality": string;
        /** @description Facebook debug information for troubleshooting */
        "X-FB-Debug": string;
        /** @description Facebook Graph API version used for the request */
        "facebook-api-version": string;
        /** @description Business use case usage metrics and rate limiting information */
        "x-business-use-case-usage": string;
        /** @description Unique identifier for the request for debugging purposes */
        "x-fb-request-id": string;
        /** @description Facebook internal revision number */
        "x-fb-rev": string;
        /** @description Facebook trace identifier for request tracking */
        "x-fb-trace-id": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPhoneNumberSettings: {
        parameters: {
            query?: {
                /** @description Include SIP credentials in the response (requires additional permissions) */
                include_sip_credentials?: boolean;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                Version: string;
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current phone number settings retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumberSettingsResponse"];
                };
            };
            /** @description Bad Request - Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Forbidden - Template not approved or insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    updatePhoneNumberSettings: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                Version: string;
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CallingSettingsRequest"] | components["schemas"]["UserIdentityChangeSettingsRequest"] | components["schemas"]["PayloadEncryptionSettingsRequest"] | components["schemas"]["StorageConfigurationSettingsRequest"];
            };
        };
        responses: {
            /** @description Settings updated successfully */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["Access-Control-Allow-Origin"];
                    "Alt-Svc": components["headers"]["Alt-Svc"];
                    "Cache-Control": components["headers"]["Cache-Control"];
                    Connection: components["headers"]["Connection"];
                    "Content-Length": components["headers"]["Content-Length"];
                    Date: components["headers"]["Date"];
                    Expires: components["headers"]["Expires"];
                    Pragma: components["headers"]["Pragma"];
                    "Strict-Transport-Security": components["headers"]["Strict-Transport-Security"];
                    Vary: components["headers"]["Vary"];
                    "X-FB-Connection-Quality": components["headers"]["X-FB-Connection-Quality"];
                    "X-FB-Debug": components["headers"]["X-FB-Debug"];
                    "facebook-api-version": components["headers"]["facebook-api-version"];
                    "x-business-use-case-usage": components["headers"]["x-business-use-case-usage"];
                    "x-fb-request-id": components["headers"]["x-fb-request-id"];
                    "x-fb-rev": components["headers"]["x-fb-rev"];
                    "x-fb-trace-id": components["headers"]["x-fb-trace-id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
            /** @description Bad Request - Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Forbidden - Template not approved or insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
