/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Media-ID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                Version: string;
                "Media-ID": string;
            };
            cookie?: never;
        };
        /**
         * Retrieve Media URL
         * @description To retrieve your media’s URL, make a **GET** call to **`/{{Media-ID}}`**. Use the returned URL to download the media file. Note that clicking this URL (i.e. performing a generic GET) will not return the media; you must include an access token. For more information, see [Download Media](https://developers.facebook.com/docs/business-messaging/whatsapp/business-phone-numbers/media#download-media).
         *
         *     You can also use the optional query **`?phone_number_id`** for **`Retrieve Media URL`** and **`Delete Media`**. This parameter checks to make sure the media belongs to the phone number before retrieval or deletion.
         *
         *     #### Response
         *
         *     A successful response includes an object with a media URL. The URL is only valid for 5 minutes. To use this URL, see [Download Media](https://developers.facebook.com/docs/business-messaging/whatsapp/business-phone-numbers/media#download-media).
         */
        get: operations["retrieveMediaUrl"];
        put?: never;
        post?: never;
        /**
         * Delete Media
         * @description To delete media, make a **DELETE** call to the ID of the media you want to delete.
         *
         *     ## Prerequisites
         *     - [User Access Token](https://developers.facebook.com/docs/facebook-login/access-tokens#usertokens) with **`whatsapp_business_messaging`** permission
         *     - Media object ID from either uploading media endpoint or media message Webhooks
         */
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    retrieveMediaUrl: {
        parameters: {
            query?: {
                /** @description Specifies that this action only be performed if the media belongs to the provided phone number. */
                phone_number_id?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                Version: string;
                "Media-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieve Media URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 303833 */
                        file_size?: string;
                        /** @example 2621233374848975 */
                        id?: string;
                        /** @example whatsapp */
                        messaging_product?: string;
                        /** @example image/jpeg */
                        mime_type?: string;
                        /** @example <HASH> */
                        sha256?: string;
                        /** @example <URL> */
                        url?: string;
                    };
                };
            };
        };
    };
    deleteMedia: {
        parameters: {
            query?: {
                /** @description Specifies that deletion of the media  only be performed if the media belongs to the provided phone number. */
                phone_number_id?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
                /** @description Media type of the request body */
                "Content-Type": "application/json" | "application/x-www-form-urlencoded" | "multipart/form-data";
            };
            path: {
                Version: string;
                "Media-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete Media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
}
