/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Business-ID}/extendedcredits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Extended Credit Lines
         * @description Retrieve extended credit line information for a business account, including
         *     balances, credit availability, ownership, and billing details.
         */
        get: operations["getExtendedCreditLines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Extended credit line associated with a business account */
        ExtendedCreditLine: {
            /**
             * @description Unique identifier for the extended credit line
             * @example 1972385232742146
             */
            id?: string;
            credit_type?: components["schemas"]["ExtendedCreditType"];
            balance?: components["schemas"]["CurrencyAmount"];
            credit_available?: components["schemas"]["CurrencyAmount"];
            max_balance?: components["schemas"]["CurrencyAmount"];
            online_max_balance?: components["schemas"]["CurrencyAmount"];
            allocated_amount?: components["schemas"]["CurrencyAmount"];
            /**
             * @description Partition source for the credit line
             * @example 9876543210987654
             */
            partition_from?: string;
            /** @description Business that owns this credit line */
            owner_business?: {
                /**
                 * @description Unique identifier for the owning business
                 * @example 9876543210987654
                 */
                id?: string;
                /**
                 * @description Name of the owning business
                 * @example Example Business Corp
                 */
                name?: string;
            };
            /**
             * @description Name of the business that owns this credit line
             * @example Example Business Corp
             */
            owner_business_name?: string;
            /**
             * @description Whether this credit line uses automated experience
             * @example false
             */
            is_automated_experience?: boolean;
            /**
             * @description Legal entity name associated with the credit line
             * @example Lucky Shrub LLC
             */
            legal_entity_name?: string;
            /**
             * @description Name of the business to send bills to
             * @example Lucky Shrub Billing
             */
            send_bill_to_biz_name?: string;
            /**
             * @description Name of the liable business
             * @example Lucky Shrub LLC
             */
            liable_biz_name?: string;
            /** @description Credit allocation configuration for receiving credentials */
            receiving_credit_allocation_config?: {
                /** @description Unique identifier for the allocation config */
                id?: string;
                /** @description Type of credit allocation partition */
                partition_type?: string;
                currency_amount?: components["schemas"]["CurrencyAmount"];
            };
            /**
             * @description Whether access to this credit line has been revoked
             * @example false
             */
            is_access_revoked?: boolean;
            /**
             * @description Whether shared credit line is enabled for managed partner accounts
             * @example false
             */
            is_shared_credit_line_enabled_for_mpa?: boolean;
        };
        /**
         * @description Type of extended credit
         * @example WHATSAPP_BUSINESS
         * @enum {string}
         */
        ExtendedCreditType: "ADS_BUSINESS" | "ADS_SEQUENTIAL" | "APP2USER" | "PAY_LATER" | "UNSPECIFIED" | "WHATSAPP_BUSINESS";
        /** @description Currency amount with formatting details */
        CurrencyAmount: {
            /**
             * @description Formatted currency amount
             * @example 1000.00
             */
            amount?: string;
            /**
             * @description Amount in hundredths (minor currency units)
             * @example 100000
             */
            amount_in_hundredths?: string;
            /**
             * @description ISO 4217 currency code
             * @example USD
             */
            currency?: string;
            /**
             * @description Offset amount in minor currency units
             * @example 100000
             */
            offsetted_amount?: string;
        };
        /** @description Response containing the list of extended credit lines */
        ExtendedCreditsResponse: {
            /** @description Array of extended credit line entries */
            data?: components["schemas"]["ExtendedCreditLine"][];
            paging?: components["schemas"]["CursorPaging"];
        };
        /** @description Cursor-based pagination information */
        CursorPaging: {
            cursors?: {
                /** @description Cursor pointing to the start of the page */
                before?: string;
                /** @description Cursor pointing to the end of the page */
                after?: string;
            };
            /** @description URL for the previous page of results */
            previous?: string;
            /** @description URL for the next page of results */
            next?: string;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /** @description More specific error subcode */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Whether this error is temporary
                 * @example false
                 */
                is_transient?: boolean;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getExtendedCreditLines: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated list of fields to include in the response.
                 *     Available fields: id, credit_type, balance, credit_available, max_balance,
                 *     online_max_balance, allocated_amount, partition_from, owner_business,
                 *     owner_business_name, is_automated_experience, legal_entity_name,
                 *     send_bill_to_biz_name, liable_biz_name, receiving_credit_allocation_config,
                 *     is_access_revoked, is_shared_credit_line_enabled_for_mpa
                 * @example id,legal_entity_name,credit_available,balance
                 */
                fields?: string;
                /**
                 * @description When true, reorders results so owning credentials appear before receiving credentials.
                 * @example true
                 */
                order_by_is_owned_credential?: boolean;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description The unique identifier of the Meta Business Portfolio
                 * @example 1234567890123456
                 */
                "Business-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extended credit lines retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtendedCreditsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Insufficient permissions to access extended credits\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Business not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
