/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Business-ID}/owned_whatsapp_business_accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Owned WhatsApp Business Accounts
         * @description Retrieve WhatsApp Business Accounts owned by the specified business. This endpoint
         *     provides comprehensive information about all WABAs owned by the business, including
         *     account details, configuration, and status information.
         *
         *     **Use Cases:**
         *     - Retrieve all WhatsApp Business Accounts owned by a business
         *     - Filter accounts by business type
         *     - Find specific accounts by ID
         *     - Monitor business portfolio of WhatsApp Business Accounts
         *     - Manage account access and permissions across multiple WABAs
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         *
         *     **Caching:**
         *     Account information can be cached for short periods, but status and configuration
         *     may change frequently. Implement appropriate cache invalidation strategies.
         */
        get: operations["getOwnedWhatsAppBusinessAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description WhatsApp Business Account owned by the business */
        WhatsAppBusinessAccount: {
            /**
             * @description Unique identifier for the WhatsApp Business Account
             * @example 104996122399160
             */
            id: string;
            /**
             * @description Human-readable name of the WhatsApp Business Account
             * @example Lucky Shrub
             */
            name: string;
            /**
             * @description Namespace identifier for message templates associated with this account
             * @example 58e6d318_b627_4112_b9c7_2961197553ea
             */
            message_template_namespace: string;
            /**
             * @description Timezone identifier for the WhatsApp Business Account
             * @example 1
             */
            timezone_id: string;
        };
        /**
         * @description Type of WhatsApp Business Account
         * @example ENTERPRISE
         * @enum {string}
         */
        WhatsAppBusinessType: "ENTERPRISE" | "SMB";
        /**
         * @description Filter for accounts based on onboarding status
         * @example ONBOARDED
         * @enum {string}
         */
        WhatsAppBusinessAccountOnboardingFilter: "ONBOARDED" | "NOT_ONBOARDED" | "ALL";
        /** @description Paginated collection of owned WhatsApp Business Accounts */
        WhatsAppBusinessAccountsConnection: {
            /** @description Array of owned WhatsApp Business Account records */
            data: components["schemas"]["WhatsAppBusinessAccount"][];
            paging?: components["schemas"]["CursorPaging"];
        };
        /** @description Cursor-based pagination information */
        CursorPaging: {
            cursors?: {
                /**
                 * @description Cursor pointing to the start of the page of data that has been returned
                 * @example QVFIUnpPVXRnY3BPN19rTVItOG51T291YURjV3BaeXRXU29adDVreS04ekhSNl9YWTlfdmN3SHlyTEk1a2FRdnlWanBqM1FuQm1uZAHhfYl9UMTNCYjM3MWV3
                 */
                before?: string;
                /**
                 * @description Cursor pointing to the end of the page of data that has been returned
                 * @example QVFIUjBrRUs5QVJuUDhDSmZARMlc2dXRYNXBmMjMtRUt3SmFlbk9PRk43azdiN1VQaW1HcnRkejFzZATNoNDdTdGVWMDhjamVvY25HWnI4WjIzX0hYSk40NHhB
                 */
                after?: string;
            };
            /**
             * @description URL for the next page of results
             * @example https://graph.facebook.com/v25.0/1234567890/owned_whatsapp_business_accounts?after=QVFIUjBrRUs5QVJuUDhDSmZARMlc2dXRYNXBmMjMtRUt3SmFlbk9PRk43azdiN1VQaW1HcnRkejFzZATNoNDdTdGVWMDhjamVvY25HWnI4WjIzX0hYSk40NHhB
             */
            next?: string;
            /**
             * @description URL for the previous page of results
             * @example https://graph.facebook.com/v25.0/1234567890/owned_whatsapp_business_accounts?before=QVFIUnpPVXRnY3BPN19rTVItOG51T291YURjV3BaeXRXU29adDVreS04ekhSNl9YWTlfdmN3SHlyTEk1a2FRdnlWanBqM1FuQm1uZAHhfYl9UMTNCYjM3MWV3
             */
            previous?: string;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOwnedWhatsAppBusinessAccounts: {
        parameters: {
            query?: {
                /**
                 * @description Filter accounts by business type. Can specify multiple types as comma-separated values.
                 *     Use this to filter between enterprise and small-medium business accounts.
                 * @example {
                 *       "0": "ENTERPRISE",
                 *       "1": "SMB"
                 *     }
                 */
                business_type?: components["schemas"]["WhatsAppBusinessType"][];
                /**
                 * @description Cursor for forward pagination. Use the cursor from the previous response
                 *     to get the next page of results.
                 * @example QVFIUjBrRUs5QVJuUDhDSmZARMlc2dXRYNXBmMjMtRUt3SmFlbk9PRk43azdiN1VQaW1HcnRkejFzZATNoNDdTdGVWMDhjamVvY25HWnI4WjIzX0hYSk40NHhB
                 */
                after?: string;
                /**
                 * @description Number of results to return in forward pagination. Maximum value is 100.
                 *     Use with 'after' cursor for forward pagination.
                 * @example 25
                 */
                first?: number;
                /**
                 * @description Cursor for backward pagination. Use the cursor from the previous response
                 *     to get the previous page of results.
                 * @example QVFIUnpPVXRnY3BPN19rTVItOG51T291YURjV3BaeXRXU29adDVreS04ekhSNl9YWTlfdmN3SHlyTEk1a2FRdnlWanBqM1FuQm1uZAHhfYl9UMTNCYjM3MWV3
                 */
                before?: string;
                /**
                 * @description Number of results to return in backward pagination. Maximum value is 100.
                 *     Use with 'before' cursor for backward pagination.
                 * @example 25
                 */
                last?: number;
                /**
                 * @description Find a specific WhatsApp Business Account by ID within the owned accounts.
                 *     Use this to quickly locate a specific account.
                 * @example 104996122399160
                 */
                find?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your Business ID. This ID represents the business portfolio that owns the
                 *     WhatsApp Business Accounts and can be found in your Business Manager settings.
                 * @example 1234567890123456
                 */
                "Business-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved owned WhatsApp Business Accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppBusinessAccountsConnection"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter: business_id must be a valid numeric string",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to access this business's WhatsApp Business Accounts\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Business ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Business not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "The requested filter combination is not supported\n",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
