/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{WhatsApp-Business-Account-ID}/assigned_users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assigned Users
         * @description Retrieve a list of users assigned to the WhatsApp Business Account with their permissions
         *     and user details. This endpoint supports pagination and filtering capabilities.
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         *
         *     **Caching:**
         *     User assignment data can be cached for short periods, but permission changes may occur
         *     frequently. Implement appropriate cache invalidation strategies.
         */
        get: operations["getAssignedUsers"];
        put?: never;
        /**
         * Add User to WhatsApp Business Account
         * @description Add a user to the WhatsApp Business Account with specified permission tasks.
         *     This operation grants the user access to perform specific actions on the account
         *     based on the provided permission tasks.
         *
         *     **Permission Tasks:**
         *     Different permission tasks grant access to different WhatsApp Business Account features:
         *     - MANAGE: General account management permissions
         *     - DEVELOP: Development and API access permissions
         *     - MANAGE_TEMPLATES: Message template management
         *     - MANAGE_PHONE: Phone number management
         *     - MESSAGING: Send and receive messages
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         */
        post: operations["addAssignedUser"];
        /**
         * Remove User from WhatsApp Business Account
         * @description Remove a user's access from the WhatsApp Business Account. This operation revokes
         *     all permissions and access rights for the specified user on the account.
         *
         *     **Important Notes:**
         *     - This operation removes ALL permissions for the user on this WhatsApp Business Account
         *     - The user will lose access to all account features and data
         *     - This action cannot be undone - the user must be re-added if access is needed again
         *     - Webhooks may be triggered to notify of user access changes
         *
         *     **Rate Limiting:**
         *     Standard Graph API rate limits apply. Use appropriate retry logic with exponential backoff.
         */
        delete: operations["removeAssignedUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description User assigned to WhatsApp Business Account with permissions */
        AssignedUser: {
            /**
             * @description Unique identifier for the assigned user
             * @example 1234567890123456
             */
            id: string;
            /**
             * @description Display name of the assigned user
             * @example John Smith
             */
            name: string;
            business?: components["schemas"]["BusinessNode"];
            user_type?: components["schemas"]["AssignedUserType"];
        };
        /**
         * @description Type of user assignment
         * @example BUSINESS_USER
         * @enum {string}
         */
        AssignedUserType: "BUSINESS_USER" | "SYSTEM_USER" | "PERSONAL_USER";
        /** @description Business entity associated with the user */
        BusinessNode: {
            /**
             * @description Unique identifier for the business
             * @example 9876543210987654
             */
            id?: string;
            /**
             * @description Name of the business
             * @example Example Business Inc
             */
            name?: string;
        };
        /**
         * @description Granular permission tasks for WhatsApp Business Account access
         * @example MANAGE
         * @enum {string}
         */
        WhatsAppBusinessAccountPermissionTask: "MANAGE" | "DEVELOP" | "MANAGE_TEMPLATES" | "MANAGE_PHONE" | "VIEW_COST" | "MANAGE_EXTENSIONS" | "VIEW_PHONE_ASSETS" | "MANAGE_PHONE_ASSETS" | "VIEW_TEMPLATES" | "MESSAGING";
        /** @description Response containing list of assigned users with pagination */
        AssignedUsersResponse: {
            /** @description Array of assigned users */
            data: components["schemas"]["AssignedUser"][];
            paging?: components["schemas"]["CursorPaging"];
            summary?: components["schemas"]["AssignedUsersSummary"];
        };
        /** @description Summary information about assigned users */
        AssignedUsersSummary: {
            /**
             * @description Total number of assigned users
             * @example 25
             */
            total_count?: number;
        };
        /** @description Cursor-based pagination information */
        CursorPaging: {
            cursors?: {
                /**
                 * @description Cursor pointing to the start of the page of data
                 * @example QVFIUmx1WTBpMGpJWXprYzVYaVhabW9PVVhF
                 */
                before?: string;
                /**
                 * @description Cursor pointing to the end of the page of data
                 * @example QVFIUjJ5M2wwdmtONVFHbDZAMVQ4OGJBQUFBQQ
                 */
                after?: string;
            };
            /**
             * @description Graph API endpoint for the next page of results
             * @example https://graph.facebook.com/v25.0/1234567890123456/assigned_users?access_token=YOUR_SYSTEM_USER_ACCESS_TOKEN&limit=25&after=QVFIUjJ5M2wwdmtONVFHbDZAMVQ4OGJBQUFBQQ
             */
            next?: string;
            /**
             * @description Graph API endpoint for the previous page of results
             * @example https://graph.facebook.com/v25.0/1234567890123456/assigned_users?access_token=YOUR_SYSTEM_USER_ACCESS_TOKEN&limit=25&before=QVFIUmx1WTBpMGpJWXprYzVYaVhabW9PVVhF
             */
            previous?: string;
        };
        /** @description Standard success response for write operations */
        SuccessResponse: {
            /**
             * @description Indicates whether the operation was successful
             * @example true
             */
            success: boolean;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
                /**
                 * @description User-friendly error title for display purposes
                 * @example Permission Denied
                 */
                error_user_title?: string;
                /**
                 * @description User-friendly error message for display purposes
                 * @example Your app doesn't have permission to access this resource
                 */
                error_user_msg?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAssignedUsers: {
        parameters: {
            query: {
                /**
                 * @description Business ID that owns or has access to the WhatsApp Business Account.
                 *     This parameter is required to specify the business context for user assignments.
                 * @example 9876543210987654
                 */
                business: string;
                /**
                 * @description Comma-separated list of fields to include in the response. If not specified,
                 *     default fields will be returned (id, name). Available fields: id, name, business, user_type
                 * @example id,name,business,user_type
                 */
                fields?: string;
                /**
                 * @description Maximum number of assigned users to return per page. Default is 25, maximum is 100.
                 * @example 25
                 */
                limit?: number;
                /**
                 * @description Cursor for pagination. Use this to get the next page of results.
                 * @example QVFIUjJ5M2wwdmtONVFHbDZAMVQ4OGJBQUFBQQ
                 */
                after?: string;
                /**
                 * @description Cursor for pagination. Use this to get the previous page of results.
                 * @example QVFIUmx1WTBpMGpJWXprYzVYaVhabW9PVVhF
                 */
                before?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business Account ID. This ID is provided when you create the account
                 *     and can be found in your Business Manager or through account management APIs.
                 * @example 1234567890123456
                 */
                "WhatsApp-Business-Account-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved assigned users list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignedUsersResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "The parameter business is required to specify a business\n",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Need permission on WhatsAppBusinessAccount or this Business\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - WhatsApp Business Account ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "WhatsApp Business Account not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "The requested fields are not available for this account\n",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
    addAssignedUser: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business Account ID. This ID is provided when you create the account
                 *     and can be found in your Business Manager or through account management APIs.
                 * @example 1234567890123456
                 */
                "WhatsApp-Business-Account-ID": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /**
                     * @description User ID of the person to add to the WhatsApp Business Account.
                     *     This must be a valid Facebook user ID.
                     * @example 2345678901234567
                     */
                    user: string;
                    /**
                     * @description Array of permission tasks to grant to the user. These tasks determine
                     *     what actions the user can perform on the WhatsApp Business Account.
                     * @example {
                     *       "0": "MANAGE",
                     *       "1": "DEVELOP",
                     *       "2": "MANAGE_TEMPLATES"
                     *     }
                     */
                    tasks: components["schemas"]["WhatsAppBusinessAccountPermissionTask"][];
                };
            };
        };
        responses: {
            /** @description Successfully added user to WhatsApp Business Account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter: user must be a valid user ID",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to add users to this WhatsApp Business Account\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - WhatsApp Business Account ID or User ID does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "WhatsApp Business Account not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "User is already assigned to this WhatsApp Business Account\n",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
    removeAssignedUser: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v25.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business Account ID. This ID is provided when you create the account
                 *     and can be found in your Business Manager or through account management APIs.
                 * @example 1234567890123456
                 */
                "WhatsApp-Business-Account-ID": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /**
                     * @description User ID of the person to remove from the WhatsApp Business Account.
                     *     This must be a valid Facebook user ID that is currently assigned to the account.
                     * @example 2345678901234567
                     */
                    user: string;
                };
            };
        };
        responses: {
            /** @description Successfully removed user from WhatsApp Business Account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter: user must be a valid user ID",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to remove users from this WhatsApp Business Account\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "error_user_title": "Permission Denied",
                     *         "error_user_msg": "Your app doesn't have permission to access this resource\n"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - WhatsApp Business Account ID or User ID does not exist or is not assigned */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "User is not assigned to this WhatsApp Business Account\n",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Cannot remove user due to business asset group permissions\n",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
