/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{Version}/{Phone-Number-ID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve WhatsApp Business Phone Number Information
         * @description Retrieve comprehensive information about a WhatsApp Business phone number using its unique ID (CSID).
         *     This endpoint provides phone number status, verification details, quality metrics, and configuration information.
         *
         *     **Core Information Returned:**
         *     - Phone number ID and display format
         *     - Verification status and verified business name
         *     - Quality rating based on message delivery performance
         *     - Code verification status for two-step verification
         *     - Display name certification status (when requested)
         *
         *     **Quality Rating System:**
         *     The quality rating reflects how recipients have been receiving messages from this phone number:
         *     - **GREEN**: High quality - messages are being delivered and engaged with well
         *     - **YELLOW**: Medium quality - some delivery or engagement issues detected
         *     - **RED**: Low quality - significant delivery or engagement problems
         *     - **NA**: Quality rating not yet determined (new phone numbers)
         *
         *     **Display Name Status:**
         *     When requesting the `name_status` field, you'll receive the current certification status:
         *     - **APPROVED**: Business name verified and certificate available for download
         *     - **AVAILABLE_WITHOUT_REVIEW**: Certificate ready without additional review required
         *     - **DECLINED**: Business name verification rejected
         *     - **EXPIRED**: Existing certificate has expired and needs renewal
         *     - **PENDING_REVIEW**: Name verification request is under review
         *     - **NONE**: No certificate or verification request exists
         *
         *     **Code Verification Status:**
         *     Indicates the two-step verification status:
         *     - **VERIFIED**: Phone number has completed two-step verification
         *     - **UNVERIFIED**: Two-step verification is pending or incomplete
         *
         *     **Use Cases:**
         *     - Monitor phone number quality and delivery performance
         *     - Check verification and certification status
         *     - Validate phone number configuration before sending messages
         *     - Retrieve display information for business profiles
         *     - Audit phone number compliance and status
         *
         *     For more information on quality ratings, see [WhatsApp Business Account Message Quality Rating](https://www.facebook.com/business/help/896873687365001).
         */
        get: operations["getPhoneNumberById"];
        put?: never;
        /**
         * Update WhatsApp Business Account Phone Number Status and Configuration
         * @description Update the status and configuration of a WhatsApp Business Account phone number.
         *     This endpoint supports comprehensive phone number management including status updates,
         *     webhook configuration, security settings, and business profile management.
         *
         *     **Supported Operations:**
         *     - Update connection status between WhatsApp Business Account and phone number
         *     - Configure webhook endpoints for message delivery notifications
         *     - Set up two-step verification and security notifications
         *     - Update display names for name verification
         *     - Configure search visibility and privacy settings
         *     - Set username for the WhatsApp Business Account
         *     - Override webhook callback URIs for message notifications
         *
         *     **Business Logic Requirements:**
         *     - App must be linked to the WhatsApp Business Account
         *     - Webhook subscription must exist before configuring callback URI overrides
         *     - Callback URI verification is performed for external URLs
         *     - Internal URLs are allowed for development environments
         *
         *     **Rate Limiting:**
         *     WhatsApp use case throttling applies. Use appropriate retry logic with exponential backoff.
         *
         *     **Security Validations:**
         *     - App-to-WABA linking validation enforced
         *     - Webhook callback URI verification required for external URLs
         *     - Business integration system user checks for AI bot onboarding
         *     - Capability checks for first-party app access
         */
        post: operations["updatePhoneNumberStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Phone number information and status */
        PhoneNumberInfo: {
            /**
             * @description The ID associated with the phone number
             * @example 1906385232743451
             */
            id?: string;
            /**
             * @description The string representation of the phone number
             * @example +1 631-555-5555
             */
            display_phone_number?: string;
            /**
             * @description The verified name associated with the phone number
             * @example Jasper's Market
             */
            verified_name?: string;
            /**
             * @description The quality rating of the phone number based on how messages have been received by recipients in recent days.
             *     - GREEN: High Quality
             *     - YELLOW: Medium Quality
             *     - RED: Low Quality
             *     - NA: Quality has not been determined
             * @example GREEN
             * @enum {string}
             */
            quality_rating?: "GREEN" | "YELLOW" | "RED" | "NA";
            /**
             * @description The two-step verification status for the phone number indicating whether the number has completed two-step verification.
             *     - VERIFIED: Phone number has completed two-step verification
             *     - UNVERIFIED: Two-step verification is pending or incomplete
             * @example VERIFIED
             * @enum {string}
             */
            code_verification_status?: "VERIFIED" | "UNVERIFIED";
            /**
             * @description The status of a display name associated with a specific phone number.
             *     - APPROVED: The name has been approved. You can download your certificate now.
             *     - AVAILABLE_WITHOUT_REVIEW: The certificate for the phone is available and display name is ready to use without review.
             *     - DECLINED: The name has not been approved. You cannot download your certificate.
             *     - EXPIRED: Your certificate has expired and can no longer be downloaded.
             *     - PENDING_REVIEW: Your name request is under review. You cannot download your certificate.
             *     - NONE: No certificate is available.
             * @example AVAILABLE_WITHOUT_REVIEW
             * @enum {string}
             */
            name_status?: "APPROVED" | "AVAILABLE_WITHOUT_REVIEW" | "DECLINED" | "EXPIRED" | "PENDING_REVIEW" | "NONE";
        };
        /** @description Request to send a message via WhatsApp Business API */
        MessageRequest: {
            /**
             * @description Messaging service used for the request
             * @example whatsapp
             * @enum {string}
             */
            messaging_product: "whatsapp";
            /**
             * @description Type of recipient
             * @default individual
             * @example individual
             * @enum {string}
             */
            recipient_type: "individual" | "group";
            /**
             * @description Recipient's phone number (with country code) or group ID
             * @example +1234567890
             */
            to: string;
            /**
             * @description Type of message being sent
             * @example text
             * @enum {string}
             */
            type: "text" | "image" | "audio" | "video" | "document" | "location" | "contacts" | "template" | "interactive" | "reaction" | "sticker";
            text?: components["schemas"]["TextMessage"];
            context?: components["schemas"]["MessageContext"];
        };
        TextMessage: {
            /**
             * @description Text content of the message
             * @example Hello, this is a test message!
             */
            body: string;
            /**
             * @description Whether to show URL preview
             * @default false
             * @example false
             */
            preview_url: boolean;
        };
        MessageContext: {
            /**
             * @description ID of message being replied to
             * @example wamid.HBgLMTY3NzE4NDM4NjAVAgARGBI5QTRCMEM4RjA2NzY4RTlBNAA=
             */
            message_id?: string;
        };
        /** @description Request to update phone number settings */
        SettingsRequest: {
            calling?: components["schemas"]["CallingSettings"];
        };
        CallingSettings: {
            /**
             * @description Enable or disable calling feature
             * @example enabled
             * @enum {string}
             */
            status: "enabled" | "disabled";
            /**
             * @description Control visibility of the call icon
             * @example visible
             * @enum {string}
             */
            call_icon_visibility?: "visible" | "hidden";
        };
        RegisterRequest: {
            /**
             * @description Messaging service used for the request
             * @example whatsapp
             * @enum {string}
             */
            messaging_product: "whatsapp";
            /**
             * @description 6-digit PIN for two-step verification
             * @example 123456
             */
            pin: string;
        };
        VerifyCodeRequest: {
            /**
             * @description 6-digit verification code received via SMS or voice
             * @example 123456
             */
            code: string;
        };
        TwoStepVerificationRequest: {
            /**
             * @description 6-digit PIN for two-step verification
             * @example 123456
             */
            pin: string;
        };
        /** @description Request to update phone number status and configuration */
        PhoneNumberStatusUpdateRequest: {
            connection_status?: components["schemas"]["WhatsAppBusinessAccountToNumberStatus"];
            /**
             * Format: uri
             * @description Webhook URL for receiving message notifications
             * @example https://your-domain.com/webhook
             */
            webhook_url?: string;
            whatsapp_business_api_data?: components["schemas"]["WhatsAppBusinessApiData"];
            /**
             * @description Two-step verification PIN (can be empty string)
             * @example 123456
             */
            pin?: string;
            search_visibility?: components["schemas"]["WAAPIBusinessGlobalSearchStateStatus"];
            webhook_configuration?: components["schemas"]["WebhookConfiguration"];
            /**
             * @description New display name for name verification request
             * @example My Business Name
             */
            new_display_name?: string;
            /**
             * @description Username for the WhatsApp Business Account
             * @example mybusiness
             */
            username?: string;
        };
        /** @description WhatsApp Business API configuration data */
        WhatsAppBusinessApiData: {
            /**
             * @description Two-step verification PIN (can be empty string)
             * @example 123456
             */
            pin?: string;
            /**
             * @description Whether to show security notifications
             * @example true
             */
            show_security_notifications?: boolean;
            /**
             * @description Whether to notify users when changing number
             * @example false
             */
            notify_user_change_number?: boolean;
        };
        /** @description Webhook configuration settings */
        WebhookConfiguration: {
            /**
             * Format: uri
             * @description Override callback URI for webhook notifications (can be empty string)
             * @example https://your-domain.com/webhook/override
             */
            override_callback_uri: string;
            /**
             * @description Token used to verify webhook requests
             * @example YOUR_VERIFY_TOKEN
             */
            verify_token?: string;
        };
        /**
         * @description Connection status between WhatsApp Business Account and phone number
         * @example CONNECTED
         * @enum {string}
         */
        WhatsAppBusinessAccountToNumberStatus: "CONNECTED" | "DISCONNECTED" | "PENDING" | "FLAGGED" | "RESTRICTED" | "RATE_LIMITED" | "MESSAGING_LIMIT_TIER_0" | "MESSAGING_LIMIT_TIER_1" | "MESSAGING_LIMIT_TIER_2" | "MESSAGING_LIMIT_TIER_3" | "MESSAGING_LIMIT_TIER_4";
        /**
         * @description Search visibility status for the WhatsApp Business Account
         * @example VISIBLE
         * @enum {string}
         */
        WAAPIBusinessGlobalSearchStateStatus: "VISIBLE" | "HIDDEN";
        /** @description Response from sending a message */
        MessageResponse: {
            /**
             * @description Messaging service
             * @example whatsapp
             * @enum {string}
             */
            messaging_product: "whatsapp";
            /** @description Contact information */
            contacts: components["schemas"]["ContactResponse"][];
            /** @description Message information */
            messages: components["schemas"]["MessageResponseItem"][];
        };
        ContactResponse: {
            /**
             * @description Input phone number
             * @example +1234567890
             */
            input: string;
            /**
             * @description WhatsApp ID
             * @example 1234567890
             */
            wa_id?: string;
        };
        MessageResponseItem: {
            /**
             * @description Message ID
             * @example wamid.HBgLMTY3NzE4NDM4NjAVAgARGBI5QTRCMEM4RjA2NzY4RTlBNAA=
             */
            id: string;
        };
        /** @description Generic success response */
        SuccessResponse: {
            /**
             * @description Operation success status
             * @example true
             */
            success: boolean;
        };
        /** @description Standard Graph API error response */
        GraphAPIError: {
            error: {
                /**
                 * @description Human-readable error message
                 * @example Invalid parameter
                 */
                message: string;
                /**
                 * @description Error category type
                 * @example OAuthException
                 */
                type: string;
                /**
                 * @description Numeric error code
                 * @example 100
                 */
                code: number;
                /**
                 * @description More specific error subcode when available
                 * @example 33
                 */
                error_subcode?: number;
                /**
                 * @description Unique identifier for debugging and support requests with Meta
                 * @example AXsgnV2Cm3ZMGF3dF_cfYIn
                 */
                fbtrace_id?: string;
                /**
                 * @description Indicates whether this error is temporary and the request should be retried
                 * @example false
                 */
                is_transient?: boolean;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPhoneNumberById: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated list of additional fields to include in the response. If not specified,
                 *     only default fields (id, display_phone_number, verified_name, quality_rating) are returned.
                 *
                 *     **Available Fields:**
                 *     - `name_status`: Display name certification status for business verification
                 *     - `code_verification_status`: Two-step verification status for the phone number
                 *
                 *     **Field Values:**
                 *
                 *     **name_status** values:
                 *     - `APPROVED`: Business name approved, certificate available for download
                 *     - `AVAILABLE_WITHOUT_REVIEW`: Certificate ready without additional review
                 *     - `DECLINED`: Business name verification rejected
                 *     - `EXPIRED`: Certificate expired and needs renewal
                 *     - `PENDING_REVIEW`: Name verification under review
                 *     - `NONE`: No certificate or verification request exists
                 *
                 *     **code_verification_status** values:
                 *     - `VERIFIED`: Phone number has completed two-step verification
                 *     - `UNVERIFIED`: Two-step verification pending or incomplete
                 */
                fields?: string;
            };
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 *     Use the latest stable version for optimal performance and feature support.
                 * @example v23.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business Account phone number ID (CSID). This unique identifier is assigned when you
                 *     register the phone number with WhatsApp Business API and can be found in your WhatsApp Business Manager.
                 * @example 106853218861309
                 */
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Successfully retrieved phone number information. The response includes core phone number details
             *     and any additional fields requested via the `fields` parameter.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumberInfo"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Phone number ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Too Many Requests - Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
    updatePhoneNumberStatus: {
        parameters: {
            query?: never;
            header: {
                /** @description The user agent string identifying the client software making the request. */
                "User-Agent"?: string;
                /** @description Bearer token for API authentication. This should be a valid access token obtained through the appropriate OAuth flow or system user token. */
                Authorization: string;
            };
            path: {
                /**
                 * @description Graph API version to use for this request. Determines the API behavior and available features.
                 * @example v23.0
                 */
                Version: string;
                /**
                 * @description Your WhatsApp Business Account phone number ID (CSID). This ID is provided when you
                 *     register the phone number and can be found in your WhatsApp Business Manager.
                 * @example 1234567890123456
                 */
                "Phone-Number-ID": string;
            };
            cookie?: never;
        };
        /**
         * @description Configuration parameters for updating phone number status and settings.
         *     All parameters are optional and can be combined in a single request.
         */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PhoneNumberStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Operation completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"] | components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Bad Request - Invalid parameters or malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid parameter: recipient phone number format is incorrect",
                     *         "type": "OAuthException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unauthorized - Invalid or missing access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Invalid OAuth access token",
                     *         "type": "OAuthException",
                     *         "code": 190,
                     *         "error_subcode": 463,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Forbidden - Insufficient permissions or access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Your app doesn't have permission to access this phone number\n",
                     *         "type": "OAuthException",
                     *         "code": 200,
                     *         "error_subcode": 1349174,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Not Found - Phone number ID does not exist or is not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Phone number not found",
                     *         "type": "GraphMethodException",
                     *         "code": 803,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Unprocessable Entity - Request parameters are valid but cannot be processed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "The phone number is not registered",
                     *         "type": "GraphMethodException",
                     *         "code": 100,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Too Many Requests - Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "Application request limit reached",
                     *         "type": "OAuthException",
                     *         "code": 4,
                     *         "error_subcode": 2446079,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
            /** @description Internal Server Error - Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "message": "An unexpected error occurred. Please retry your request\n",
                     *         "type": "GraphMethodException",
                     *         "code": 2,
                     *         "fbtrace_id": "AXsgnV2Cm3ZMGF3dF_cfYIn",
                     *         "is_transient": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GraphAPIError"];
                };
            };
        };
    };
}
