name: Prepare CI cache
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  prepare-yarn-cache:
    name: Prepare npm cache for ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --prefer-offline --frozen-lockfile
