name: Test
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
        shard: [1/1]
    name: Node v${{ matrix.node-version }} on ${{ inputs.os }} ${{ matrix.shard }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm run build
      - run: node --import tsx --test --test-shard=${{ matrix.shard }}
          src/__tests__/unit/**/*.test.ts src/__tests__/unit/*.test.ts
