name: Test
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  node_test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]
        shard: [1/1]
    name:
      Node v${{ matrix.node-version }} on ${{ inputs.os }} ${{ matrix.shard }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm run build
      - run:
          node --import tsx --test --test-shard=${{ matrix.shard }}
          src/__tests__/unit/**/*.test.ts src/__tests__/unit/*.test.ts

  deno_test:
    strategy:
      fail-fast: false
      matrix:
        deno-version: [v2.x]
        shard: [1/1]
    name:
      Deno v${{ matrix.deno-version }} on ${{ inputs.os }} ${{ matrix.shard }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test:integration:deno

  bun_test:
    strategy:
      fail-fast: false
      matrix:
        bun-version: [1.2.20]
        shard: [1/1]
    name: Bun v${{ matrix.bun-version }} on ${{ inputs.os }} ${{ matrix.shard }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test:integration:bun
